export GIT_REPO_NAME=data_analysis_presentations
cd /Users/mertnuhoglu/projects/dewey/data_analysis_presentations/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=jsutils_mn
cd /Users/mertnuhoglu/projects/jsutils_mn/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=mertnuhoglu.com
cd /Users/mertnuhoglu/projects/jekyll/mertnuhoglu.com/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=mertnuhoglu.com_2015
cd /Users/mertnuhoglu/projects/jekyll/mertnuhoglu.com_2015/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=my-vim-custom
cd /Users/mertnuhoglu/projects/vim_repos/my-vim-custom/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=nuhogluvakfi
cd /Users/mertnuhoglu/projects/nuhogluvakfi/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=nuhogluvakfi01
cd /Users/mertnuhoglu/projects/jekyll/nuhogluvakfi01/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=rutils
cd /Users/mertnuhoglu/projects/rutils/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=secim_verileri
cd /Users/mertnuhoglu/projects/dewey/secim_verileri/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=study_data
cd /Users/mertnuhoglu/projects/study_data/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
export GIT_REPO_NAME=stuff
cd /Users/mertnuhoglu/projects/stuff/
sh ~/projects/study/logbook/ex/log_20200415/sync_git_repos/git_seturl.sh
git push
