acksed "stnd/analysis" "stnd, \#prd/analysis"
acksed "stnd/analysis_communication" "stnd, \#prd/analysis/communication"
acksed "stnd/causal_analysis" "stnd, \#org/causal_analysis"
acksed "stnd/data_quality" "stnd, \#org/data_quality"
acksed "stnd/decision_analysis" "stnd, \#org/decision_analysis"
acksed "stnd/design" "stnd, \#prd/design"
acksed "stnd/development" "stnd, \#prd/development"
acksed "stnd/documentation" "stnd, \#org/documentation"
acksed "stnd/estimation" "stnd, \#prd/estimation"
acksed "stnd/figma" "stnd, \#tll/figma"
acksed "stnd/graphics_design" "stnd, \#prd/graphics_design"
acksed "stnd/measurement" "stnd, \#org/measurement"
acksed "stnd/problem-cozme" "stnd, \#org/problem-solving"
acksed "stnd/process_management" "stnd, \#org/process_management"
acksed "stnd/product_review" "stnd, \#prd/product_review"
acksed "stnd/project_management" "stnd, \#prd/project_management"
acksed "stnd/quality" "stnd, \#org/quality"
acksed "stnd/risk_management" "stnd, \#org/risk_management"
acksed "stnd/siniflandirma" "stnd, \#tpc/classification"
acksed "stnd/transition_to_production" "stnd, \#prd/transition_to_production"
acksed "stnd/user_manual" "stnd, \#prd/user_manual"
acksed "stnd/youtrack" "stnd, \#tll/youtrack"

acksed "ekip/gnd"	"ekip, gnd"
acksed "grsm/tst"	"grsm, tst"
acksed "p/engin/gnd"	"p/engin, gnd"
acksed "pcm/rpa"	"org/pcm/rpa"
acksed "tpc/oryantasyon"	"org/orientation"
acksed "work/piyasa-arastirmasi"	"org/market-research"

acksed "\#ekip/gnd"	"\#ekip, \#gnd"
acksed "\#grsm/tst"	"\#grsm, \#tst"
acksed "\#p/engin/gnd"	"\#p/engin, \#gnd"
acksed "\#pcm/rpa"	"\#org/pcm/rpa"
acksed "\#rdb"	"\#prd/rdb"
acksed "\#tpc/oryantasyon"	"\#org/orientation"
acksed "\#ui"	"\#prd/ui"
acksed "\#vim"	"\#tll/vim"
acksed "\#wtng"	"\#gtd/wtng"
acksed "\#yöntem"	"\#tpc/method"
acksed "\#work/piyasa-arastirmasi"	"\#org/market-research"

acksed "\#geribildirim" "\#frm/feedback"
acksed "\#msg" "\#frm/msg"
acksed "\#mtng" "\#frm/mtng"
acksed "\#ndx" "\#frm/ndx"
acksed "\#rtc" "\#frm/rtc"
acksed "\#qst" "\#frm/qst"
acksed "\#qry" "\#frm/qry"
acksed "\#query" "\#frm/qry"
acksed "\#prb" "\#frm/prb"
acksed "\#pln" "\#frm/pln"
acksed "\#review" "\#frm/review"

acksed "\#analiz" "\#prd/analysis"
acksed "\#analysis" "\#prd/analysis"
acksed "\#barış" "\#p/baris"
acksed "\#branding" "\#org/branding"
acksed "\#calisma-ortami" "\#org/tll"
acksed "\#clj" "\#prg/clj"
acksed "\#clj/clerk" "\#prj/clj/clerk"
acksed "\#clj/datomic" "\#prg/datomic"
acksed "\#clj/electric" "\#prg/clj/electric"
acksed "\#clojure" "\#prg/clj"
acksed "\#cmmi" "\#org/cmmi"
acksed "\#cms" "\#prj/cms"
acksed "\#code-review" "\#org/code-review"
acksed "\#data-model" "\#org/data-modelling"
acksed "\#data-modelling" "\#org/data-modelling"
acksed "\#documentation" "\#org/documentation"
acksed "\#doğukan" "\#p/dogukan"
acksed "\#ekip" "\#p/ekip"
acksed "\#fkr" "\#fkr"
acksed "\#g/engin" "\#p/engin"
acksed "\#git" "\#tll/git"
acksed "\#graphics-design" "\#prd/graphics-design"
acksed "\#grsm/branding" "\#org/branding"
acksed "\#gtd/mert" "\#p/mert"
acksed "\#intellij" "\#tll/intellij"
acksed "\#kslt" "\#opal/kslt"
acksed "\#management" "\#org/management"
acksed "\#market/competition" "\#org/market"
acksed "\#mockup" "\#prd/mockup"
acksed "\#org/dijital-pazarlama" "\#org/marketing/digital"
acksed "\#org/planlama" "\#org/planning"
acksed "\#p/doğukan" "\#p/dogukan"
acksed "\#pazarlama" "\#org/marketing"
acksed "\#procurement" "\#prj/pms"
acksed "\#strategy/roadmap" "\#org/strategy/roadmap"
acksed "\#strategy/technology" "\#org/strategy/technology"
acksed "\#terminal" "\#prg/terminal"
acksed "\#tpc/terminal" "\#prg/terminal"
acksed "\#training" "\#org/training"
acksed "\#orientation"	"\#org/orientation"
acksed "\#oryantasyon"	"\#org/orientation"
acksed "\#p/pms"	"\#prj/pms"

# tags:: line
#
