---
title: "Study Handsontable"
date: 2018-04-19T11:19:56+03:00
draft: true
description: ""
tags:
categories: js
type: post
url:
author: "Mert Nuhoglu"
output: html_document
blog: mertnuhoglu.com
resource_files:
- 
path: ~/projects/study/js/study_handsontable.Rmd
wip: true
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

Source code in https://github.com/mertnuhoglu/study/js/ex/study_handsontable/

## ex01: make a static handsontable

``` bash
mkdir -p ex/study_handsontable/ex01 && cd $_
``` 

Edit `~/projects/study/js/ex/study_handsontable/ex01/index.js`

``` js
open ex/study_handsontable/ex01/index.html
``` 

## ex02_01: render(): Update handsontable: data from js to handsontable

``` bash
mkdir -p ex/study_handsontable/ex02 && cd $_
cp ../ex01/* .
``` 

Edit `ex/study_handsontable/ex02/index.js`

``` js
...
hot1 = new Handsontable(container1, settings1);
data1[0][1] = 'Ford'; // change "Kia" to "Ford" programmatically
hot1.render();
``` 

## ex02_02: error: unknown cause

https://docs.handsontable.com/2.0.0/Core.html#loadData

I used the code from official documentation. But it doesn't work. 

Edit `ex/study_handsontable/ex02/db.json`

``` json
{
  "data": [["","Ford","Nissan","Toyota","Honda","Mazda","Ford"],["2017",10,11,12,13,15,16],["2018",10,11,12,13,15,16],["2019",10,11,12,13,15,16],["2020",10,11,12,13,15,16],["2021",10,11,12,13,15,16]]
}
``` 

``` bash
json-server --watch ex/study_handsontable/ex02/db.json --port 3001
``` 

## ex02_03: loadData() to update data

Edit `ex/study_handsontable/ex02/index03.js`

``` js
...
hot1 = new Handsontable(container1, settings1);
data1[0][1] = 'Ford'; // change "Kia" to "Ford" programmatically
hot1.render();
...
hot1.loadData(data2)
``` 

`hot1.loadData` updates handsontable widget on browser with new data.

## ex02_04: use RxJs to feed data

Edit `ex/study_handsontable/ex02/index04.js`

``` js
...
var hot1 = new Handsontable(container1, settings1);
const t$ = Rx.Observable.timer(0, 2000).map(i => 2*i)
t$.subscribe( i => {
	data1[0][i % 7] = i; 
	hot1.loadData(data1)
})
``` 

## ex03: read from handsontable to js: getSourceData

``` bash
mkdir -p ex/study_handsontable/ex03 && cd $_
cp ../ex02/index.* .
``` 

Edit `ex/study_handsontable/ex03/index.js`

``` js
console.log(hot1.getSourceData())
  ##> Array(2)
  ##> 0: (7) ["", "Ford", "Nissan", "Toyota", "Honda", "Mazda", "Ford"]
  ##> 1: (7) ["2017", 10, 11, 12, 13, 15, 16]
console.log(JSON.stringify(hot1.getSourceData()))
  ##> "[["","Ford","Nissan","Toyota","Honda","Mazda","Ford"],["2017",10,11,12,13,15,16]]"
``` 

## ex04: get data after each change: afterChange()

React uses afterChange()

https://github.com/handsontable/react-handsontable/issues/1

https://codepen.io/handsoncode/pen/LWmvPX?editors=0010

``` bash
mkdir -p ex/study_handsontable/ex04 && cd $_
cp ../ex03/index.* .
``` 

Edit `ex/study_handsontable/ex04/index.js`

``` js
...
hot1.addHook('afterChange', function () {
  console.log(hot1.getSourceData())
})
``` 

## ex05: Use objects as data source

Edit `~/projects/study/js/ex/study_handsontable/ex05/index.js`
