---
title: "Study Notes: Mostly adequate guide to FP"
date: 2018-02-16T14:22:38+03:00  
draft: true 
description: ""
tags:
categories: js, fp
type: post
url:
author: "Mert Nuhoglu"
output: html_document
blog: mertnuhoglu.com
resource_files:
-
path: ~/projects/study/js/study_frisby_book_adequate_guide_to_fp.Rmd
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

## Chapter 04: Currying

This is how currying can be defined in a simple way:

```{js}
// curry :: ((a, b, ...) -> c) -> a -> b -> ... -> c
function curry(fn) {
  const arity = fn.length;

  return function $curry(...args) {
    if (args.length < arity) {
      return $curry.bind(null, ...args);
    }

    return fn.call(null, ...args);
  };
}
```

Now, let's use `curry` for partial application:

```{js}
const match = curry((regex, s) => s.match(regex));
match(/r/g, 'hello world'); // ["r"]
const hasLetterR = match(/r/g); // x => x.match(/r/g)
hasLetterR('hello world'); // [ 'r' ]
```

Argument order: Note that last argument is the most varying argument. This is the actual data.

### Wrapping With `map`

This may be the most important benefit of currying: 

Wrapping a curried function with `map`, makes the function work on arrays.

<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>

```{js}
const CDN = s => `https://cdnjs.cloudflare.com/ajax/libs/${s}`;
const ramda = CDN('ramda/0.21.0/ramda.min');
requirejs.config({ paths: { ramda } });
require(['ramda'], ({ compose, curry, map, prop }) => {
  const allHasLetterR = map(hasLetterR);
  const xs = ['world', 'ali'];
  allHasLetterR(xs);
  // [Array(1), null]
});
2 + 1;
```

Therefore, we don't need to define functions that work on arrays if we can define them on single elements using `sort`, `filter`, `map` and other higher order functions.

### Exercises

Refactor by partially applying arguments:

    // words :: String -> [String]
    const words = str => split(' ', str);
    --->>>
    const words = split(' ');

Refactor by partially applying arguments:

    // filterQs :: [String] -> [String]
    const filterQs = xs => filter(x => x.match(/q/i), xs);
    --->>>
    const filterQs = filter(match(/q/i));

Refactor by partially applying arguments:

    const keepHighest = (x, y) => (x >= y ? x : y);
    // max :: [Number] -> Number
    const max = xs => reduce((acc, x) => (x >= acc ? x : acc), -Infinity, xs);
    --->>>
    const max = reduce(keepHighest, -Infinity)

Definition of curry:

    // curry :: ((a, b, ...) -> c) -> a -> b -> ... -> c
    function curry(fn) {
      const arity = fn.length;
      return function $curry(...args) {
        if (args.length < arity) {
          return $curry.bind(null, ...args);
        }
        return fn.call(null, ...args);
      };
    }

## Chapter 05: Composing

Definition of compose:

    const compose = (f, g) => x => f(g(x));

x: value being piped through f and g

mnemonics: composition order:

    Which one first?

    First g, then f

    Reverse order (f,g)

    First g means: g inside

### Debugging

Common problem with composing `map`

`map` takes two arguments:: (x->x) -> xs -> xs

We need to first partially apply `map` in order to make it single argument function:

Ex:

    const angry = compose(exclaim, toUpperCase);
    var reverse = reduce( (acc,x) => [x].concat(acc), [])
    //wrong - we end up giving angry an array and we partially applied map with god knows what.
    var latin = compose(map, angry, reverse);
    latin(['frog', 'eyes']);
    // error because:
    -> reverse(['frog', 'eyes']) -> angry(['eyes', 'frog']) // error
    --->>>
    var latin = compose(map(angry), reverse);
    latin(['frog', 'eyes']);
    // ['EYES!', 'FROG!'])

Note: `map(angry)` takes one input

    map(angry) :: xs -> xs

Use `trace` to debug any error:

    const trace = curry((tag, x) => {
      console.log(tag, x);
      return x;
    });

    const dasherize = compose(
      join('-'),
      toLower,
      trace('after split'),
      split(' '),
      replace(/\s{2,}/ig, ' '),
    );

    dasherize('The world is a vampire');
    // after split [ 'The', 'world', 'is', 'a', 'vampire' ]

### Exercises

`prop` definition:

    // prop :: String -> Object -> a
    const prop = curry((p, obj) => obj[p]);

Use `compose`:

    // isLastInStock :: [Car] -> Boolean
    const isLastInStock = (cars) => {
      const lastCar = last(cars);
      return prop('in_stock', lastCar);
    };
    --->>>
    const isLastInStock = compose(prop('in_stock'), last);

Make it a composition:

    const average = xs => reduce(add, 0, xs) / xs.length;
    // averageDollarValue :: [Car] -> Int
    const averageDollarValue = (cars) => {
      const dollarValues = map(c => c.dollar_value, cars);
      return average(dollarValues);
    };
    --->>>
    const averageDollarValue = compose(average, map(prop('dollar_value')));

Make it a composition:

    // fastestCar :: [Car] -> String
    const fastestCar = (cars) => {
      const sorted = sortBy(car => car.horsepower, cars);
      const fastest = last(sorted);
      return concat(fastest.name, ' is the fastest');
    };
    --->>>
    const append = flip(concat);
    const fastestCar = compose(
      append(' is the fastest'),
      prop('name'),
      last,
      sortBy(prop('horsepower')),
    );

Definition of flip:

    // flip :: (a -> b) -> (b -> a)
    const flip = curry((fn, a, b) => fn(b, a));

## ch06: Flickr App Example

### mnemonics

Assume that:

    const f = curry( (x,y) => ... )

Then first call puts single argument into the first position. Second call puts the argument into the next position:

    f(x)(y)

Assume that:

    const Impure = {
      getJSON: curry((callback, url) => $.getJSON(url, callback)),
      setHtml: curry((sel, html) => $(sel).html(html)),
      trace: curry((tag, x) => { console.log(tag, x); return x; }),
    }; 
    const app = compose(Impure.getJSON(Impure.trace('response')), url);

Consider:

    Impure.getJSON(Impure.trace('response'))

Type signatures of the curried functions are:

    Impure.trace('response') :: a -> a
    Impure.getJSON :: (a->a) -> a -> j
    Impure.getJSON(Impure.trace('response')) :: a -> j

