#!/usr/bin/env bb

; Özlü sözler (aforizmalar) id=g14127
; Aphorisms and quotes 
; Source: https://gist.githubusercontent.com/wunki/abeca1633bac6069718e079f80f0eb27/raw/7eb620509de48cbb28b2486fe6e5dc4e8943b285/inspiration.clj
; Source: https://github.com/Azel4231/clojure-quotes/blob/master/generated.md

(require '[clojure.string :as str])

(def user (str/capitalize
           (str (System/getenv "USER"))))

(def words-of-inspiration
  (list 
    ; Source: https://gist.githubusercontent.com/wunki/abeca1633bac6069718e079f80f0eb27/raw/7eb620509de48cbb28b2486fe6e5dc4e8943b285/inspiration.clj
    "The best way to predict the future is to invent it. -Alan Kay"
    "A point of view is worth 80 IQ points. -Alan Kay"
    "Lisp isn't a language, it's a building material. -Alan Kay"
    "Simple things should be simple, complex things should be possible. -Alan Kay"
    "Everything should be as simple as possible, but not simpler. -Albert Einstein"
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. -Bill Gates"
    "Controlling complexity is the essence of computer programming. -Brian Kernighan"
    "The unavoidable price of reliability is simplicity. -C.A.R. Hoare"
    "You're bound to be unhappy if you optimize everything. -Donald Knuth"
    "Simplicity is prerequisite for reliability. -Edsger W. Dijkstra"
    "Elegance is not a dispensable luxury but a quality that decides between success and failure. -Edsger W. Dijkstra"
    "Deleted code is debugged code. -Jeff Sickel"
    "The key to performance is elegance, not battalions of special cases. -Jon Bentley and Doug McIlroy"
    "First, solve the problem. Then, write the code. -John Johnson"
    "Simplicity is the ultimate sophistication. -Leonardo da Vinci"
    "Programming is not about typing... it's about thinking. -Rich Hickey"
    "Design is about pulling things apart. -Rich Hickey"
    "Programmers know the benefits of everything and the tradeoffs of nothing. -Rich Hickey"
    "Code never lies, comments sometimes do. -Ron Jeffries"
    "The true delight is in the finding out rather than in the knowing. -Isaac Asimov"
    "If paredit is not for you, then you need to become the sort of person that paredit is for. -Phil Hagelberg"
    "Express Yourself. -Madonna"
    "Put on your red shoes and dance the blues. -David Bowie"
    "Do. Or do not. There is no try. -Yoda"
    "The enjoyment of one's tools is an essential ingredient of successful work. -Donald E. Knuth"
    "Not all those who wander are lost. -J.R.R. Tolkien"
    "The best way to learn is to do. -P.R. Halmos"
    "If you wish to make an apple pie from scratch, you must first invent the universe. -Carl Sagan"
    "Learn the rules like a pro, so you can break them like an artist. -Pablo Picasso"
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. -Arthur C. Clarke"
    "Don't wish it were easier. Wish you were better. -Jim Rohn"
    "One chord is fine. Two chords is pushing it. Three chords and you're into jazz. -Lou Reed"
    "We are all apprentices in a craft where no one ever becomes a master. -Ernest Hemingway"
    "A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. -Antoine de Saint-Exupery"
    "Clojure isn't a language, it's a building material."
    "Think big!"
    "Think bold!"
    "Think fun!"
    "Code big!"
    "Code bold!"
    "Code fun!"
    "Let the hacking commence!"
    "Hacks and glory await!"
    "Hack and be merry!"
    "Your hacking starts... NOW!"
    "May the Source be with you!"
    "Code long and prosper!"
    "Happy hacking!"
    "Fame is but a hack away!"
    "Keep on codin' in the free world!"
    "Evaluating is believing."
    "To infinity... and beyond."
    "Showtime!"
    "Unfortunately, no one can be told what CIDER is. You have to figure this out yourself."
    "Procure a bottle of cider to achieve optimum programming results."
    "In parentheses we trust!"
    "Write you some Clojure for Great Good!"
    "Oh, what a day... what a lovely day!"
    "What a day! What cannot be accomplished on such a splendid day!"
    "The worst day programming is better than the best day working."
    "In the absence of parentheses, chaos prevails."
    "May your functions be pure, your code concise and your programs a joy to behold!"
    (format "%s, I've a feeling we're not in Kansas anymore." user)
    (format "%s, this could be the start of a beautiful program." user)
    "Scientifically-proven optimal words of hackerish encouragement."
    ; Source: https://github.com/Azel4231/clojure-quotes/blob/master/generated.md
    "Data-first programming. In the end I want my language concerned about data transformations. I don't want OOP where I'm constantly converting a \"Person\" to a \"Student\". I don't want a language where I'm considered \"doing it wrong\" if I keep all my data in a hashmap or a vector. (Rules out pretty much everything but Clojure) - Timothy Baldridge"
    "Well Clojure ends up being so concise that you're not very likely too see code that's in the millions of lines of code. [..] If you assume a 100x code savings in Clojure vs Java (true for most of the projects I've worked on), you're left with 10,000 lines of Clojure code. And I've worked on a ton of those. - Timothy Baldridge"
    "So as my friend always says: \"static typing doesn't solve problems I have\" - Timothy Baldridge"
    "Whatever you background, Clojure is almost guaranteed to affect the way you think about programming. - Eli Bendersky"
    "It's chock-full of great ideas. In other words, the perfect language to expand your brain. - Eli Bendersky"
    "Because Clojure is seriously good shit, and it has been for over a decade. - Brandon Bloom"
    "Clojure Spec is one of the most exciting things to happen in Clojure land, and probably programming in general, in a while. - Arne Brasseur"
    "When I chase down an odd bug in my code, I usually end up learning about the accidental complexity of some tech stack. When I chase down an odd bug in my Clojure code, I usually learn something about good design. - Kurt Christensen"
    "A lot of the best programmers and the most productive programmers I know are writing everything in Clojure and swearing by it, and then just producing ridiculously sophisticated things in a very short time. And that programmer productivity matters. - Adrien Cockroft"
    "Clojure feels incredibly fluid and malleable, it’s both extremely powerful (because of its abstractions) and also extremely simple (it’s a small language, with a handful of consistent concepts). It’s great for exploring simple problems, and for building large, complex systems - Sean Corfield"
    "What I like most about Clojure is that it is fun to use! - Sean Corfield"
    "I never perfectly understand the problem while I'm solving it. My code materializes my understanding, so it's never perfect either. As my understanding improves, the code follows it. For me, it's important that the programming language supports that fluidity. #Clojure - Dragan Djuric"
    "The learning curve is significant but the advantages are tremendous. I wholeheartedly recommend learning Clojure even if you're not allowed to use it at your job. It sounds cliché, but it will make you a better programmer for sure. - Oliver Eidel"
    "It's not just about concision. Yes, it's nice that you can do this in nine lines. But what's really cool about it is because I didn't need to sit down an specify all these classes about what my data was gonna look like ahead of time, I ended up with code that's more general. - Mark Engelberg"
    "We often say we should use the right tool for the right job. And it's absolutely true. It's an interesting expression though. I haven't heard anyone apply it to a tool that they didn't like. - Tim Ewald"
    "It's all just chisels. All the way down - Tim Ewald"
    "There's always a limit [to automated tools]. And it affects what you do. - Tim Ewald"
    "The tools that you use shape how you look at the world. - Tim Ewald"
    "I want tools that enable me do unique things. Tools that don't change my perspective. [...] And I believe Clojure is a perfect toolset for doing this. - Tim Ewald"
    "IOC, the injection of complexity - Tim Ewald"
    "I'll be forever grateful to Rich for giving us a toolset that is mercilessly and mercifully simple. It's merciless in its pursuit of simplicity, and in giving us that, it's merciful to us. - Tim Ewald"
    "Clojure is great for apps where you need access to the bare meta. - Jay Fields"
    "At the conceptual level of what the application is doing, it's nearly always a flow of data through your program. And how you're manipulating that data. And all the rest is just the noise around that. That is one of the big philosophical revelations that Clojure is helping with. - Colin Fleming"
    "TDD. But not the one you think I'm talking about. [Test Driven Dentistry]. And what that means is: not everything should be test driven. - Michael Fogus"
    "Do you ever feel like you're being boilerplated alive? - Michael Fogus"
    "Well-formed Data at rest is as close to perfection in programming as it gets. All the crap that had to happen to put it there however.. - Michael Fogus"
    "When we first started exploring Clojure we thought we were getting a hobby language. That's what I used it for and that's the way I viewed it. But now, ten years later, what I actually got was a language that I can base a career on. - Michael Fogus"
    "Clojure recently crossed a threshold. There are people in this room that can spend the rest of their career writing Clojure code. - Michael Fogus"
    "Clojure does for concurrency what Java did for memory management - Neal Ford"
    "To build a brand new language and use lisp syntax on the JVM, you either gotta be a crazy person, or got some really cool ulterior motive. I met Rich and he's not a crazy person. - Neal Ford"
    "Meta-programming in Clojure is just programming - Neal Ford"
    "In Clojure, because the language is so bendable, you actually bend language towards the problem, not the problem towards the language. - Neal Ford"
    "People ask me what projects I would choose Clojure for. The answer is: the nastiest, hardest, toughest kinds of projects possible. Because it's those projects where you need the ability to mold your language towards your problem, not vice versa - Neal Ford"
    "The two most sophisticated projects we have going on in the world right now, are both Clojure projects, on purpose. Because we think this is the only way these projects can be done. - Neal Ford"
    "With Clojure you are bringing a gun to a knife fight - Neal Ford"
    "'What is your favorite non-Java JVM language?' 'That one's a pretty easy one and that's Clojure. And the reason for that is that I think Clojure is one of the few production quality, serious JVM languages that isn't just 'Let's do Java better.'' - Brian Goetz"
    "If you have more things than names, your design is broken - Stuart Halloway"
    "If there are more concepts than names [in a diagram], it's not simple yet - Stuart Halloway"
    "'This class remains empty, only used for the above annotations'. We know you're doing some good complexity when you find yourself having to say things like that - Stuart Halloway"
    "Nothing says 'Screw You!' like a DSL - Stuart Halloway"
    "All that stuff we have done about encoding data in the Clojure ecosystem and in the Datomic ecosystem wouldn't have to exist, if JSON didn't suck - Stuart Halloway"
    "We're trying to shrink the elephant-in-the-room-factor. - Stuart Halloway"
    "Universal schema sounds buzzwordy. I you want to categorize it in a contrarian way, you can say 'It completely solves ORM'. - Stuart Halloway"
    "[In Datomic] you can navigate in both directions. This is strictly awesome compared to being in an object-oriented environment, where one direction is blessed. - Stuart Halloway"
    "You know what's web-scale? The Web. And you know what it is? Dynamically typed. - Stuart Halloway"
    "There's a way to approach this where this doesn't have to feel like a trade-off. Where it's all winning. You can program in the most generic way possible and still deal with the specifics. And that's what clojure.spec does. - Stuart Halloway"
    "This slide is essentially the replacement for OO. - Stuart Halloway"
    "I wanna think about the number of times that I was building a web application and my stakeholder said: 'You know, the users really like this, but I'm not sure if the type system in your language is decidable'. It just doesn't come up very often. - Stuart Halloway"
    "Simplicity makes you feel powerful because you're going exactly in the direction that you want to go. - Stuart Halloway"
    "The only thing that Java is actually concise at is interface declarations.  - Stuart Halloway"
    "There are some details of implementation inheritance that can't be duplicated in Clojure. Implementation inheritance is evil. - Stuart Halloway"
    "Ok Rich, we got simple and power, but can we please have just a little tiny bit of easy somewhere? Just a smidge. - Stuart Halloway"
    "I've thought about how to actually do the Clojure version of that. So you would come to a conference and you would set up a hammock. You would clojurize and people would watch you for half an hour. And then you'd say 'Aha!' and stand up and leave. - Stuart Halloway"
    "One line of think, per one line of code. - Stuart Halloway"
    "What's the dollar cost of having gotten [data serialization] wrong? [...] I bet it's billions of dollars spent because we have our architecture layers inverted. - Stuart Halloway"
    "Java reflection epitomizes OO design. And it's piss pour. - Stuart Halloway"
    "It's in fact so bad, that I would argue that POJO is an oxymoron. The only thing POJOs look plain next to is EJBs. - Stuart Halloway"
    "And all that just gets worse at scale. So all the problems that are baked into OO just snowball as things get bigger. - Stuart Halloway"
    "OO is not dead here, it's just be dissected. So when you look at writing code in Clojure, and you say 'Well this doesn't look like OO at all', it's not that OO is dead an gone. It's that all the pieces of OO have been dissected and delivered separately. - Stuart Halloway"
    "One of the things that happens when you write a Clojure program is that in your design you will probably identify all of the mutable state in the program. That will be a list that fits on an index card in most cases. And all the parts that are not that, you get to treat in a wholly different way. They're pure functions, they're easy to reason about, they're easy to test. And that's a whole world of better. - Stuart Halloway"
    "Clojure has a really strong notion of namespaces, which is straight-up superior to what I've seen in most OO languages. - Stuart Halloway"
    "I do think that it's actually easier to learn something that's based on composits of simples than it is to learn something that is baroque. Someone that is capable to learn enough Java to do something at all, they're capable of learning Clojure enough to do something. - Stuart Halloway"
    "If you look at what Clojure brings to Lisp, it brings the one good thing out of OO: polymorphism. - Stuart Halloway"
    "I don't wanna run down leiningen cause it's awesome. And it's been a huge help for getting the Clojure community going. And Phil and everybody else who have worked on that deserve a big wet soggy kiss when you see'em. But it's not simple. It represents heroic effort to undo harm done by others. - Stuart Halloway"
    "Cross region replication is another example of something that gets crazy easier because everything is indelible. Because you have this model it's not place-oriented programming. In order to replicate from one region to another all we have to do is stream stuff from place to place. We don't have to do any coordination that's like 'Oh my god this thing changed'. All those kinds of problems go away. It almost feels like cheating. - Stuart Halloway"
    "Commas are whitespace, so they're not shown anywhere in this notation. Most people coming from other programming languages like to see their things in their list delimited by commas. It's perfectly fine to do that [in Clojure] if you want to. Probably after a couple of weeks you'll get tired of typing the commas and start leaving them out. And then you'll start leaving them out when you're writing programs in other languages and you'll be irritated. It is a fact of life. - Stuart Halloway"
    "This is the kind of advantage that I'm talking about of writing code in a dynamic language. You end up with a very, very small number of very short very general purpose things. And these pieces all have to fit together. And if everything wasn't shorter, that would suck. Because I would still want to have the roadmaps that static typing gives me. I wouldn't wanna go here. And if I had to make as many things as I would have to make to build an OO system I'd still want the types. But I make ten times fewer things on small Clojure programs and a hundred times fewer things on large Clojure programs than I would make if I had to write them in OO. - Stuart Halloway"
    "I think we should all get into functional and then we can argue about the static and dynamic thing, once we're at the end of the road. That static/dynamic debate is really kinda tiny compared to 'we need to be more functional and less imparative'. And so I think that Clojure and F# and Scala and ML and OCaml and all these guys, we're all on the same side here. We're all fighting for truth and justice together. - Stuart Halloway"
    "[Clojure has] a learning curve that leads to expertise, not better-beginnerness. - Stuart Halloway"
    "Coding alive, against a tangible runtime, where you're in your program invoking your tools, instead of living in your tools invoking your program. - Stuart Halloway"
    "Busywork begets busywork. If the constraints of your programming language make this a good idea, is it time for a different language. - Stuart Halloway"
    "If you don't think managing state is tricky, consider the fact that 80% of all problems in all complex systems are fixed by rebooting. - Stuart Halloway"
    "I use #Clojure because the fastest way to implement nontrivial projects in #Java is to create Clojure and then use it. - Stuart Halloway"
    "#Clojure has a 10+ year record of stability that absolutely crushes the shiny-chasing JS ecosystem. Don't make your customer struggle with that needless churn. - Stuart Halloway"
    "Clojure proper: I love it. Clojurescript as well though. I don't see myself using other languages... ever. - Bruce Hauman"
    "I consider Clojure a kind of strange maximum. This may be it for a while guys! - Bruce Hauman"
    "Multiple taxonomies in a single program. That's easy in Clojure. - Rich Hickey"
    "Design is to take things apart in such a way that they can be put back together - Rich Hickey"
    "Design is separating into things that can be composed. - Rich Hickey"
    "Every time I encounter something I can boil it down to that. Every time I encounter something that I wish my design was better, I need to do more of this [take things apart]. Over and over again. I did not take it apart enough. - Rich Hickey"
    "Design helps extension. To the extent that you have broken things into separate parts, with an eye towards connecting them back together, it means that your resulting design is gonna have connection points. And when you want your system to do something new, it will be possible to do it, because there's something there. That's why design is not just about accreting up to an answer. Because when you do that you don't end up with any connecting points. And you don't end up with any building blocks. And you can't really extend that thing. "
    "It's something we don't think about often enough. In our programming designs and in our systems, about the actual costs of specificity. We love specificity. When we use Java every new idea gets a new class. What does that cause to happen? You get this explosion of code! Objects were supposed to support reuse, they have done the exact opposite thing. Especially in typed languages. You get very little reuse, because you make a new thing every time.  - Rich Hickey"
    "As a default architecture mutable objects are terrible. - Rich Hickey"
    "When you know your data can never change out from underneath you, everything is different. - Rich Hickey"
    "Simplicity is hard work. But in the long haul the person with a simpler system is gonna wipe the plate with you. Because they can change things when you are struggling to push elephants around - Rich Hickey"
    "I saw someone that was advocating that people should design their systems as systems of systems right from the get-go. Like: 'make it into six services in the first iteration'. And I said to that person: 'Wow, that seems like a lot of forethought! Why can't people morph from one system to a system of systems?'. And he said: 'You know, because of their languages and how they use them'. - Rich Hickey"
    "We can make the same software we're making today with dramatically simpler stuff. - Rich Hickey"
    "If you want everything to be familiar, you'll never learn anything new - Rich Hickey"
    "Simplicity enables change. I think it's the primary source of real agility. Agility means to do something. It doesn’t mean to do it over, it doesn’t mean to redo it, it doesn’t mean to undo it. It means to directly do. That’s agility. If you’re dragging an elephant around you’re never going to be agile - Rich Hickey"
    "If you've got the complexity elephant over there, you are applying the process to pushing elephants. And how good can you get at it? - Rich Hickey"
    "When later in my career I learned lisp, I saw people building very interesting systems out of much, much simpler stuff. - Rich Hickey"
    "And I said... Well I can't repeat it, but I was very unhappy. Basically something to the effect of 'I have been wasting my time and my career, doing what I've been doing. And need to do something, I need to change what I'm doing. Because I'm wasting my time, I'm wasting my life doing it this way.' - Rich Hickey"
    "Easiness will eventually slow you down - Rich Hickey"
    "This is the 'Information non-problem': Information is simple. This is a problem we create for ourselves. Because we ruin it by wrapping it in classes. - Rich Hickey"
    "Encapsulation is for implementation details, but information doesn't have implementation! - Rich Hickey"
    "In OO, our fundamental construct, the Object conflates two things. Process, for which objects are an ok approach, and information for which they are a terrible, terrible, terrible approach. - Rich Hickey"
    "There's a tiny little benefit: dot works in your IDE. Woohoo! Oh my goodness, cause I could never remember that [specific class API]. Something better happen when I press dot, because I'm doomed otherwise. - Rich Hickey"
    "Programs are increasingly about code, and decreasingly about data. And I think that is a mistake. - Rich Hickey"
    "Information is simple. The only thing you can do with information is ruin it - Rich Hickey"
    "leave data alone - Rich Hickey"
    "When we start writing get this, get that, there is no purpose to this. This is just life sucking. - Rich Hickey"
    "Our programming house is like a hoarder's delight: there's too much stuff in it everything is too big. We need too many people to do basic things. - Rich Hickey"
    "Why did you do that [using object's to represent data]? The answer could be: 'I was using Java, and I had no choice'. That's not a great answer. But it might be the truth. - Rich Hickey"
    "Nobody wants to program with mutable strings anymore, why do you want to program with mutable collections?  - Rich Hickey"
    "It's pretty easy to underestimate how much this is costing us in software development. I think it's basically a catastrophe- the way we approach aggregates. It's something I would really like to fix. - Rich Hickey"
    "Polymorphism à la carte completely changes the way you work - Rich Hickey"
    "A Person class or an account class, that's a ridiculous thing. You can't change an account any more than you can change the day of the week. - Rich Hickey"
    "Place itself has no role in an informationmodel. It is only an implementation detail. If you're elevating place to a first class thing in your information model, it's only an 'information model', it's pretend, it's not doing its job. - Rich Hickey"
    "Operational interfaces are specific. That generates a ton more code. It actually is a counter argument to the promise of object oriented programming. One of the promises was: reuse. This is the big lie of object oriented programming. Every new thing you have to do, you write a new class. Where's the reuse in that? - Rich Hickey"
    "Nothing composes with places - Rich Hickey"
    "Java programmers and OO programmers have been kicking SQL. 'It requires ObjectRelationalMapping, and that's like a problem with SQL'. No! It's a problem with objects. - Rich Hickey"
    "Objects are not the way the world works. Nothing in the world works that way. People don't hand their strings out to other people to start yanking on them. So that's how we're gonna have a soccer team: we're gonna have a reference to somebody else. You call pass to me. And we build this big spaghetti nightmare. This is completely not the way the world works. This is not how physics works. We say objects are a way to model the real world? It's not at all. It's a complete programming fabrication. It's not very realistic. It's not a good fit for almost anything. - Rich Hickey"
    "How many times did I say 'immutability' in this talk? Immutability rocks. One of the things that are very interesting about that is: you cannot correctly represent change without immutability. It's a profound idea. It's not my idea. It's just an essential characteristic of the universe. But it really needs to be recognized in our architectures. - Rich Hickey"
    "If I had any recommendation to you at all, it's just if you're thinking about designing a system and you're not sure, whether you can answer all that questions in the forward direction, choose immutability. You can almost back into a little more than 50% of this design just by haven taken immutability as a constraint, saying 'oh my god now what am I gonna do? I cannot change this. I better do this!' And keep forcing you into good answers. So if I had any architectural guidance from this: Just do it. Choose immutability and see where it takes you. - Rich Hickey"
    "That's just Java being Java - Rich Hickey"
    "It is my opinion that object oriented programming, as delivered by Java, etc., is not a good default way to structure your program. - Rich Hickey"
    "[In java] you are set up to do the wrong thing. - Rich Hickey"
    "State. You're doing it wrong - Rich Hickey"
    "Mutable objects are the new Spaghetti code - Rich Hickey"
    "Eventually, with mutable objects you create an intractable mess. And encapsulation does not get rid of that. Encapsulation only means: 'well I'm in charge of this mess'. - Rich Hickey"
    "Every single language that allows for mutable objects has the problem that there is no standard time management. - Rich Hickey"
    "The OO model has gotten time wrong - Rich Hickey"
    "We don't get to stop the world, especially not to observe it. - Rich Hickey"
    "All these things you always wish you had, you get. All the time. - Rich Hickey"
    "Perception is uncoordinated. It's massively parallel. It is not message passing. - Rich Hickey"
    "But we can't screw up time and state the way we have, and have it still be easier. Because it's now wrong. - Rich Hickey"
    "As we get more concurrent, we're gonna need learn to live in a world, that's gonna proceed in spite our intention or desire or best wishes that it would not. 'Cause it would be a lot easier for us if it wouldn't. It's gonna! We're not gonna achieve the degrees of parallelism and the concurrency we want until we can accept this. And embrace it. - Rich Hickey"
    "We can consume memory in order to model time. - Rich Hickey"
    "When you get hit by lightning, who's behaving? There is no behavior. - Rich Hickey"
    "I think you should pick. You should either have explicit constructs [for state] or go all the way to haskell. Because everything in between is catastrophe. - Rich Hickey"
    "Just take my word for it: persistent data structures are so much better. - Rich Hickey"
    "If you write a program that uses persistent data structures, you'll be able to sleep at night. You're gonna be happier. Your life is gonna be better. Because there's a huge quantity of things you will no longer have to worry about. - Rich Hickey"
    "It just sorta changes everything - Rich Hickey"
    "We should build the insides of our systems, like we build the outsides of our systems. All value propositions that accrue to systems - we want them! - Rich Hickey"
    "I don't know. I don't wanna know. - Rich Hickey"
    "You have to make this rationale from the systems level: 'Data orientation and dynamic typing make sense in systems. You explain to me why it doesn't inside the programs: I don't understand why it wouldn't.' - Rich Hickey"
    "Build your human interface on top of a programmatic interface, because programmatic interfaces are all you've got in the systems level - Rich Hickey"
    "One thing about abstraction is to recognize the difference between abstracting in order to simplify, and abstracting in order to hide. If abstracting is like putting paint on it, or putting it in a box and closing it because it reeks so bad. That's not good. - Rich Hickey"
    "By the time you're writing a service, there's nothing premature about abstraction. - Rich Hickey"
    "Down in the small in a program you can over-bstract, up here you can't - Rich Hickey"
    "Clojure is in a unique position in providing maybe the friendliest face ever presented to functional programming that's out there - Rich Hickey"
    "Clojure solves the problem that you don't know you have. - Rich Hickey"
    "Now, we're in ClojureScript. Do we need sugar for JavaScript? We're like chocolate syrup for JavaScript...with whipped cream and cherries and sprinkles and everything! Right. So we do not need sugar for JavaScript. And we have macros - which is like your own hot fudge machine. - Rich Hickey"
    "Learning requires inefficiency - Rich Hickey"
    "So how do we change our software? Apparently, I heard in a talk today, that Agile and Extreme Programming have shown that refactoring and tests allow us to make change with zero impact. "
    "What goes in the cache? What form does it take? When does it get invalidated? Whose problem are all these questions? Yours! Your problem! Or maybe you're buying some fancy ORM that makes it your problem with another a layer on op of your problem. Now you have two problems. - Rich Hickey"
    "Instruments are made for people who can play them. Isn't that outrageous? Isn't that scandalous? The are made for people who can actually play them. And that's a problem. Because beginners can't play. They're not yet players. The don't know how to do it. Again, I think, there should be outrage on the internet. We should submit patches. We should fix like the Cello. Should Cellos auto-tune? Or maybe they should have red and green lights. It's green when you're in tune, it's red when you're not in tune. Or maybe they shouldn't make any sound at all until you get it right. Is that how it works? is that what we want? No, that's not how it works. Look at these kid's. They're being subjected to cellos. There's nothing helping them here. [...] They're smaller but those are real cellos. They're hard to play, they're awkward, the sound terrible. They're out of tune. It's gonna be tough for a while for these kids - Rich Hickey"
    "As a simple example: here's a guitar player, a harp player, a double bass player all holding up their blisters. Imagine if you downloaded a library off the internet and it gave you blisters! The horror. And yet, every musician has overcome a barrier of entry similar to this. - Rich Hickey"
    "Clojure, I think, is completely unique amongst the languages on the JVM in promoting immutility and concurrency.   - Rich Hickey"
    "These [persistent data structures] are very different beasts. They have excellent performance, yet they're immutable. It's sort of the secret sauce of Clojure. Without these you can't do what I do in a language. - Rich Hickey"
    "One of the nice things about Clojure is that it let's you fix Java - Rich Hickey"
    "These were hard data structures to write. These took me years of research and work. But the performance is good, and the benefits are unbelievable. - Rich Hickey"
    "I think, even if you set concurrency aside, using those kind of data structures and taking a functional approach to writing your programs, is gonna give you much, much better programs. Much more reliable, much easier to test and understand and maintain. BUT, when you put concurrency in the loop, there is no longer any contest: nothing compares to using this kind of a strategy in designing your program. - Rich Hickey"
    "So the conventional way is that: eveybody is looking at the same space. And that space can get scribbled on by anybody else. And there's all this 'Wait, wait! I'm scribbling on this space'. And 'Wait! I have to see it, don't scribble on it. I'm trying to understand it'. That's how your programs work today. It's crazy. - Rich Hickey"
    "And I like to ask this question: What's true of every bug found in the field? [...] It passed the type checker. What else did it do? It passed all the tests. - Rich Hickey"
    "I think we're in this world I like to call guardrail programming. It's really sad. We're like: 'I can make change because I have tests'. Who does that? Who drives their car around banging against the guardrails saying 'Woa. I'm glad I have these guardrails. Or I'll never make it to the show on time!'. And do the guardrails help you get to where you wanna go? Like, do guardrails guide you places? No. There's guardrails everywhere. They don't point your car in any particular direction. - Rich Hickey"
    "Systems are dynamic and data driven. It might be a nice idea to use a language that was also dynamic and data driven. - Rich Hickey"
    "At this point I was an expert C++ user and really loved C++. For some value of 'love'. That involves no satisfaction at all. - Rich Hickey"
    "What does effective mean? It means 'producing the intended result'. And I really want this word to become important because I'm really tired of the word correctness. Where correctness means, I don't know, 'made the type checker happy'. None of my consumers of these programs that I did professionally care about that. They care that the program works for their definition of works. - Rich Hickey"
    "That's the problem: after 18 years of using C++ and Java, you're exhausted. How many people have been programming for 18 years? How many for more than 20 years? More than 25? Fewer than 5? So that is really interesting to me. It may be an indictment of Clojure as a beginners language. Or maybe that Clojure is the language for cranky, tired, old programmers. - Rich Hickey"
    "I had to rewrite it in C++. It took four times as long to rewrite it than to write it in the first place. It yielded five times as much code and it was no faster. And that's when I knew I was doin' it wrong. - Rich Hickey"
    "Why was I unhappy as a programmer after 18 years and said 'If I can't switch to something like CommonLisp I am gonna switch careers'? Why am I saying that? I am saying it because I'm frustrated with a bunch of limitations in what I was using. - Rich Hickey"
    "I wanted Clojure to be a good library language, but I didn't think about the library ecosystem problems as part of Clojure. My talk last year about libraries implies that I still think this is a big problem for programs. It's one of the ones that's left. After Clojure and Datomic, what's left to fix? - Rich Hickey"
    "The old Perlis quib about 'any sufficently large C or C++ program has a poorly implemented CommonLisp [implementation]' - It's so true. Again: Spring. As you get a larger system that you wanna maintain over time and deal with all those complexities I showed before, you want dynamism. You have to have it. It's not like an optional thing. It's necessary. - Rich Hickey"
    "Person is 'String x String x int x String x String x float x float' product type. A complete callous disregard for people, names, human thinking. It's crazy. - Rich Hickey"
    "There's the REPL. And people are like 'The REPL is cool because I get to try things'. And that's true, but the REPL is much cooler than that. It's cooler than that because it's an acronym. It's cooler than that because 'read' is its own thing. And what Clojure did by adding a richer set of data structures is it made Read-Print into a super-power. It wasn't just a convenience. It isn't just a way to interact with people. It isn't just a way to stream programs around or program-fragments around. It's now like: here's your free wire protocol. - Rich Hickey"
    "I would encourage you all to embrace the fact that Clojure is different. Don't be cowed by the proof people. Programming is not a solved problem. Logic should be your tool, it shouldn't be your master. You should be underneath the logic system and be applying the logic system when it works out for you. - Rich Hickey"
    "I think that this verification and whatnot is incredibly important. But it should be à la carte. Depending on what you need to do. Depending on the amount of money you have to spend. Depending on what you want to express. You should be able to pull different kinds of verification technology off the shelf and apply it. It should not be built-in. There's a diversity of needs, there's a diversity of approaches for doing it and a diversity of costs. - Rich Hickey"
    "If only there was a function called ... unform. Which there is. - Rich Hickey"
    "The first ten seconds David Nolen had this library [clojure.spec], he took his entire parser for om/next and threw it away. He specced his protocol and got a free parser with way better error messages than he had before. - Rich Hickey"
    "We can associate the semantics with the attributes and not with the aggregates. Because we have fully-qualified symbols and keywords. And obviously spec is all about that. - Rich Hickey"
    "Data is essential. We're supposed to be writing programs that manipulate it and the first thing we do is: we ruin it, intstead of using it directly. - Rich Hickey"
    "Programming is not mathematics. In mathematics you can swap any isomorphism for any other. In programming you get fired for doing that! - Rich Hickey"
    "Does the world fill out forms and fill everything out for you? All the things you'd like to know? No! It doesn't. - Rich Hickey"
    "We had a thing where we said in C++ is that: 'If it compiles it will probably work'. Like they say of Haskell. And it was equally true then as it is now. - Rich Hickey"
    "Maps are collections of keys, they are not the stuff inside the keys. If I put on a hat it does not change what my family is. I'm still part of my family. My family contained these people before, it contains the same people later. I didn't version my family when I put on a hat. But we do this all the time. - Rich Hickey"
    "It's ok to hate Java and like the JVM. That's where I'm at. - Rich Hickey"
    "Why do we base polymorphism on types alone? In the real world we don't categorize everything by a fundamental adverse type. Nobody is born a taxidriver or a painter or tall. But these typesystems work that way. You shall be tall and we'll make every decision about you based upon you being tall. Whereas most systems and most reality supports some sort of polymorphism based upon value, or current state or relationships to other things. So we need to sortof pull this stuff apart. Traditional object-orientation has put us in this rut where we can't even see the difference between these things. - Rich Hickey"
    "I don't believe in disallowing dangerous things. Because sometimes dangerous things are useful. - Rich Hickey"
    "I shouldn't dictate to you it be this particular type in order to interact with my API. That has to stop. Let people just glop stuff on so they can talk to you and not have to BE something so they can interact with you. - Rich Hickey"
    "Why does hierarchy have to be in types? Why stick it there? It's a dungeon. - Rich Hickey"
    "As long as people are writing functional languages and writing in functional languages they will serve as examples. And some younger programmers will never have seen something else and won't have to unlearn a bunch of bad habits. - Rich Hickey"
    "Certainly you wanna be doing functional programming primarily. Not that you can avoid doing anything else at all times, but that should be the default for sure. And I think you should be working in a language that makes those things idiomatic. So that you're not fighting against a different paradigm. - Rich Hickey"
    "I'd rather chew on a problem for ten days out of two weeks and code for the other four than to agilly rewrite it six times in four weeks and then sill have it be wrong. - Rich Hickey"
    "It's not all about your programming language. We all get infatuated with our programming languages. But you know what? I am actually pretty skeptical about programming languages being the key to programming. I do not think they are. They are a small part of programming. They are not the driver of programming. - Rich Hickey"
    "There will be sources of change. You can't build systems that don't have any change. But that is not something to slather all over your application. It is something to say 'I am really scared of this' - Rich Hickey"
    "Objects - especially in the very traditional sense or as delivered by languages like Java - boy, you just go on and on and on. What is a class? It's got state, it's got identity, it's got values, it's got operations. It's like a kitchen sink of stuff poured together. And every time you take one out to solve a problem you're starting with three or four strands already wrapped together. [...] These are terrible constructs form a complexity standpoint. - Rich Hickey"
    "Data. Please. We're programmers. We supposedly write data processing programs. There's all these programs that don't have any data in them. All these constructs we put around it and globbed on top of data. Data is actually really simple. There's not a tremendous number of variations in the essential nature of data. There are maps, there are sets, there are linear sequential things. There's not a lot of other conceptual categories of data. [In OO]  We create hundreds of thousands of variations that have nothing to do with the essence of the stuff, and make it hard to write programs that manipulate the essence of the stuff. We should just manipulate the essence of the stuff! - Rich Hickey"
    "Programming is not about typing, it's about thinking. - Rich Hickey"
    "Dependency hell is not a different thing than mutability hell. It is the same thing. It is mutability hell. It's just at this scale. - Rich Hickey"
    "It is a major failing of most programming languages and type systems that they are ignorant and unsupportive of a program's evolution over time. It need not be this way. Thus the [talk](https://www.youtube.com/watch?v=oyLBGkS5ICk). - Rich Hickey"
    "When you combine two pieces of data you get data. When you combine two machines you get trouble. - Rich Hickey"
    "A big deal here is programmable interfaces. And again, for this audience, that's what Clojure has been great at. We've seen this tremendous library growth because Clojure is data-oriented, all of out libraries are data-oriented. And I think we've seen so much more just inherent, transparant, incidental, accidental, no-effort interoperability between data-driven subsystems. - Rich Hickey"
    "I don't care how many you really love the syntax of your favorite language. It's inferior to data in every way. - Rich Hickey"
    "Functional languages such as Haskell, Erlang and Clojure offer powerful approaches to the problems that software developers have always faced. All of the so-called strengths of OOP can be found in these languages. - Lawrence Krubner"
    "With Clojure we found that the very very low friction to get things done enables you to do things that you'd otherwise never even consider - Orestis Markou"
    "What language is it that meets all the criteria? What language would I choose if I had to choose today? Probably Clojure! - Robert Martin"
    "All the REPL stuff is really exciting. Because I think think that's a super-power of Clojure. I really do. If we're looking for what's the game-changer, it's not machine-learning. It's not all this sort of bullshit. Because every language can do that. But they haven't got a REPL. And if they've got one it's shit. - Ray McDermott"
    "Anything complex I had done, I had done in JavaScript which obviously you can do much better in Clojurescript. I mean ClojureScript is without question the best way to do react. And React is the best JavaScript. - Mia"
    "The data parts of Clojure are fantastic. They allow us to get an amount of reuse that I never saw in any OO system I reused. Which was always the promise: there's this object and I can use it in lots of different ways. And I have not found that to be the case in practice. Whereas I find that the data centric approach and the generic programming model that Clojure provides to provide a tremendous amount of reuse. - Alex Miller"
    "A lot of big programs have some level of dynamicity in them. When you have a static type system you really have to build some sort of flexible system inside your program. Clojure does kind of the opposite. - Alex Miller"
    "Clojure is the least worst programming language I’ve ever used. - Alex Miller"
    "The result is that the few people who were open-minded and adventuresome enough to kick the tires of early Clojure and were willing to step outside their preconceived notions of what software is in the pursuit of doing it better, all (in my limited anecdotal experience) discovered that its distinctive design and careful expert implementation really did allow them to build a lot of materially better business software. - Blake Miller"
    "So although there’s no magic bullet, my feeling is that Clojure might at least qualify as a mildly-enchanted handmade titanium crossbow or something like that. - Blake Miller"
    "For me Clojure is very unique. Things like boot, javelin and hoplon are very rewarding to me. They're things, as far as my use of them, professionally to make money and to get actual work done, they're pretty much done. They do everything we need them to do. And we're moving on, you know, we're thinking about other problems now. And we don't need to keep solving these problems. And I have never experienced that before using Clojure. - Micha Niskin"
    "Using other languages I could never form the abstractions that were durable and composable enough to be used in the next project. I would always end up having to rewrite something or solve the same problem over and over again. I had never experienced actually solving a problem before. Or even thinking it was something that is worth spending your time on trying to do. Like trying to solve the problem of making websites once and for all. And that's all due to Clojure I think. - Micha Niskin"
    "If I wanna use a fairly cutting-edge programming language and yet at the same time I wanna get stuff done, I think Clojure [..] still totally owns that sweet-spot. I haven't found anything else that is both interesting as a programming language and yet at the same time I can just do real work with it. - David Nolen"
    "Defn-Podcast: \"If you couldn't write ClojureScript, what would you use? - \"Elm is really cool. Reason is interesting. ScalaJS is very impressive. But I spent 6 years on ClojureScript, so I don't have to use anything else.\"\" - David Nolen"
    "That's the secret for making things composable: start with the composition - before you even define how the thing will work - Eric Normand"
    "There's kind of a curse, I can say that. The curse is that these systems are so much more maintainable than the object-oriented systems that have been around for 20+ years now, that they don't require a lot of jobs. - Eric Normand"
    "Familiarity and simplicity are different things. You get used to crappyness. What’s happening is: the crappyness is bending your brain in such a way that it’s now ok with the crappyness. - Dan North"
    "Clojure people. You have to be smart enough to understand Clojure, to be masochistic enough to enjoy Emacs. - Dan North"
    "Because it's so simple, this made programming too easy. We should learn Emacs! - Dan North"
    "This is why I say Datomic is more relational than Oracle. Because a value of a Datomic database IS a relation over the space of the possible values for that schema. And you go from one relation to another relation. - Michael Nygard"
    "I think of Clojure as kind of the greatest hits of the last 20 or 30 years of computer science. It's like that mix tape. - Russ Olsen"
    "I think of Clojure as kind of the greatest hits of the last 20 or 30 years of computer science. It's like that mix tape from the Guardians of the Galaxy, only in software. - Russ Olsen"
    "For me the real win with choosing a immutable functional language such as Clojure is around the 2/3 mark in a project. Just when a large traditional OO system starts to buckle under it’s own gravity and the business rules become harder to reach through the applied refactorings and introduction of design patterns, this is when a Clojure code-base will shine in comparison. - Jon Pither"
    "You can't use or even read about Datomic without it starting to change the way that you think about and approach problems. - Milton Reder"
    "What we found was: Datomic was actually teaching us things we didn't know were lessons. - Milton Reder"
    "Haskell and Clojure have two different ideas for how to stop things from going wrong. Haskell's idea is: we're just going to build this framework of types. And when you stick within this framework of types, then you're limiting what can go wrong. [...] Clojure has a different idea and that's that things go wrong because they're too interconnected. The more things are interconnected, the harder it is for our brains to figure out what all the consequences of actions are. [...] Based on my experience it wasn't so much the types or the structure that caused me a problem, it was the interactions between things. - James Reeves"
    "Clojure is structured around the idea of reducing interactions, means reducing the amount of things that can go wrong. It's the only language I am aware of that persues this as a philosophy. - James Reeves"
    "Clojure stops you from doing the wrong things through isolation, whereas Haskell stops you from doing wrong things by being restrictive. - James Reeves"
    "One of the things I quite like about Clojure ist that it has this wide range of power. You have very simple things like an immutable map, which is at the lowest end of power. [...] And at the other end of the spectrum we have macros which are like the most powerful thing in Clojure. So Clojure has this kind of very wide range of, we can use limited stuff when we need to and we can use powerful stuff when wee need to. If you statically type your whole language, well you constrain your whole language. And maybe that's good in some cases, but in other cases you want more power. So Clojure allows you to be limited when you need it and powerful when you need that. - James Reeves"
    "In a Clojure world external DSL tools, or specialized code generators will not have any future. They seem just like incidental complexity, required to make working with a broken language bearable. I know, most of us do not earn their money in the Clojure world. That makes these external meta tools valuable. But not desirable.  - Falko Riemenschneider"
    "Clojure has that way of seemingly effortless materializing one’s thoughts into working code that I do not know from any other language. - Christian Stamm"
    "If you think about the grand mission that I think Rich [Hickey] has. And again I maybe putting words in his mouth here, but I think he's trying to solve programming. "
    "When I found this Clojure thing, and saw this extreme focus on simplicity. It felt like the way. The capital doubly way. - Robert Stuttaford"
    "It really felt to me very quickly, once I got my head around the basics, that it was gonna be more risky not to use this language than to use it. - Robert Stuttaford"
    "I'll be very honest. Clojure did not map to the way I thought about the world, it mapped to the way I wanted to think about the world. It was very much an unlearning not a learning. - Robert Stuttaford"
    "If you work with data, that's a great fit. And we all work with data, right? - Robert Stuttaford"
    "[With Datomic] you forget that time is passing, because you don't worry about it anymore. - Robert Stuttaford"
    "I've been using it for four years now and it still blows the top of my head off. - Robert Stuttaford"
    "It's immutable because it's immutable. It's a bit tautological. - Robert Stuttaford"
    "I would highly recommend anybody who's already in the JVM space, I pretty much think you should stop what you're doing and take a look right now. Because it's almost certainly gonna solve a whole world of hurt you may already find yourself in. - Robert Stuttaford"
    "Clojue is the bee's knees for this sort of problem. - Derek Troy-West"
    "Building systems that ingest data, transform data, retain data and return data at some point - Clojure is just at this really sweet nexus of being able to leverage the JVM and all the fine libraries that come along with it. Also being able to shed an enormous amount of cognitive load. Object modelling, object hierarchies... - Derek Troy-West"
    "Every system that I have ever built would have been better off being built in Clojure. - Derek Troy-West"
    "I did consider other stacks like SQL and using languages like python. But when I met the pros and cons of each alternative Clojure and Datomic always won, because they really solved the hard problems. - Valentin Waeselynck"
    "Any sufficiently advanced conventional Event Sourcing system contains an ad-hoc, informally-specified, bug-ridden, slow implementation of half Datomic. - Valentin Waeselynck"))

(println (rand-nth words-of-inspiration))

