
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table book (6)
\echo # filling table book (6)
COPY book (bid,title,isbn) FROM STDIN (ENCODING 'utf-8');
1	polished tu marble funded intro pennsylvania	9788014981218
2	bedford vg	9782723776547
3	trained commentary mozilla	9782723776547
4	gourmet mathematics	9782913571662
5	favors	9783956794780
6	knitting purpose creatures skins	9782723776547
\.

-- fill table reader (3)
\echo # filling table reader (3)
COPY reader (rid,firstname,lastname,born,gender,phone) FROM STDIN (ENCODING 'utf-8');
1	Eldon	Feela	1970-01-29	FALSE	6001655890
2	Kerrie	Calk	1979-03-22	FALSE	6986568412
3	Fiona	Echavarria	1960-08-05	FALSE	3753286868
\.

-- fill table borrow (4)
\echo # filling table borrow (4)
COPY borrow (borrowed,rid,bid) FROM STDIN (ENCODING 'utf-8');
2017-12-21 16:29:57	2	1
2017-12-21 16:30:57	3	2
2017-12-21 16:30:57	1	3
2017-12-21 16:28:57	2	4
\.

-- restart sequences
ALTER SEQUENCE book_bid_seq RESTART WITH 7;
ALTER SEQUENCE reader_rid_seq RESTART WITH 4;

-- analyze modified tables
ANALYZE book;
ANALYZE reader;
ANALYZE borrow;
