
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table book (6)
\echo # filling table book (6)
COPY book (bid,title,isbn) FROM STDIN (ENCODING 'utf-8');
1	palace funky	3
2	moves indeed download attendance towers answer britney	4
3	filled kent constant	6
4	engineer nearby me salmon shell bike brought	5
5	role	5
6	bumper charm gd	3
\.

-- fill table reader (3)
\echo # filling table reader (3)
COPY reader (rid,firstname,lastname,born,gender,phone) FROM STDIN (ENCODING 'utf-8');
1	Todd	Sesso	1988-01-18	FALSE	1931243076
2	Dean	Ritmiller	1979-06-07	TRUE	1272396169
3	Berry	Salos	1968-04-26	TRUE	9848238480
\.

-- fill table borrow (4)
\echo # filling table borrow (4)
COPY borrow (borrowed,rid,bid,note) FROM STDIN (ENCODING 'utf-8');
2017-12-13 07:26:12	1	1	note_493_493
2017-11-08 01:23:12	1	2	note_445_
2017-11-28 22:35:12	1	3	note_223_
2017-11-12 07:42:12	1	4	note_762_762
\.

-- restart sequences
ALTER SEQUENCE book_bid_seq RESTART WITH 7;
ALTER SEQUENCE reader_rid_seq RESTART WITH 4;

-- analyze modified tables
ANALYZE book;
ANALYZE reader;
ANALYZE borrow;
