
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table book (6)
\echo # filling table book (6)
COPY book (bid,title,isbn) FROM STDIN (ENCODING 'utf-8');
1	marvel meanwhile	1
2	pens stationery expansys hilton learning transition casting	5
3	issued ceiling ages olive lincoln moderate	5
4	societies construction markets unable portland	1
5	particles utah mask assault apparel submission panel	6
6	ohio	5
\.

-- fill table reader (3)
\echo # filling table reader (3)
COPY reader (rid,firstname,lastname,born,gender,phone,email,ip) FROM STDIN (ENCODING 'utf-8');
1	Kandra	Lewandoski	1993-08-08	FALSE	4459330731	oui.yfi@yahoo.com	10.2.236.144
2	Marylee	Verone	2000-09-24	TRUE	7610496804	qhx.jytx@yahoo.com	10.2.220.251
3	Raylene	Latshaw	1993-06-01	TRUE	9780596236	wnoxxo.flhwmuzf@yahoo.com	10.2.86.119
\.

-- fill table borrow (4)
\echo # filling table borrow (4)
COPY borrow (borrowed,rid,bid,note) FROM STDIN (ENCODING 'utf-8');
2017-11-09 06:52:08	3	1	note_21_
2017-11-10 22:16:08	1	2	note_543_543
2017-12-15 03:12:08	1	3	note_180_180_18
2017-11-07 13:46:08	1	4	note_110_
\.

-- restart sequences
ALTER SEQUENCE book_bid_seq RESTART WITH 7;
ALTER SEQUENCE reader_rid_seq RESTART WITH 4;

-- analyze modified tables
ANALYZE book;
ANALYZE reader;
ANALYZE borrow;
