
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table book (6)
\echo # filling table book (6)
COPY book (bid,title,isbn) FROM STDIN (ENCODING 'utf-8');
1	eugene guinea reproductive	1
2	defeat checklist	1
3	refrigerator	6
4	int	6
5	asking plot thousand user reconstruction use	6
6	planets porter habitat were texture motor translated	4
\.

-- fill table reader (3)
\echo # filling table reader (3)
COPY reader (rid,firstname,lastname,born,gender,phone) FROM STDIN (ENCODING 'utf-8');
1	Tayna	Kunsch	1979-05-17	FALSE	5483930039
2	Chi	Popadiuk	1985-01-06	TRUE	4120751495
3	Marcellus	Mclerran	1972-04-06	FALSE	2836656928
\.

-- fill table borrow (4)
\echo # filling table borrow (4)
COPY borrow (borrowed,rid,bid,note) FROM STDIN (ENCODING 'utf-8');
2018-07-31 01:16:15	2	1	note_56_56_56
2018-08-26 03:52:15	3	2	note_206_206_20
2018-08-28 01:35:15	2	3	note_863_863_86
2018-08-04 18:44:15	1	4	note_13_13
\.

-- restart sequences
ALTER SEQUENCE book_bid_seq RESTART WITH 7;
ALTER SEQUENCE reader_rid_seq RESTART WITH 4;

-- analyze modified tables
ANALYZE book;
ANALYZE reader;
ANALYZE borrow;
