---
title: "Study code"
date: 2019-07-17T16:02:24+03:00 
draft: true
description: ""
tags:
categories: bash, 
type: post
url:
author: "Mert Nuhoglu"
output:
  html_document:
    css: styles.css
blog: mertnuhoglu.com
resource_files:
path: ~/projects/study/code/study_code.Rmd
state: wip

---

# Tools

## Tool: mosh ssh replacement

https://mosh.org/

``` bash
brew install mosh
``` 

## nmap: network scanner

https://isc.sans.edu/diary/How+to+Find+Hidden+Cameras+in+your+AirBNB/24834

``` bash
nmap -Ap 80,8000,8080,443,8443,7443,7070,7000,22,23,21 10.5.1.0/24
``` 

## hub: github cli

https://hub.github.com/

Authorization:

Create a github token and put it into environment variable: `GITHUB_TOKEN`

Debug a command:

``` bash
env HUB_VERBOSE=1 hub ...
``` 

Create a new repo:

``` bash
hub create
``` 

### surfingkeys: vim emulation for chrome 

ref: `~/gdrive/mynotes/content/fork/surfingkeys_help.md`

``` bash
git clone http://github.com/b0o/surfingkeys-conf
``` 

``` bash
gulp install
cp build/surfingkeys.js ~/.config
``` 


#### hint characters

https://github.com/brookhong/surfingkeys

``` bash
Hints.characters = "fgouieajvc"
``` 

## broot: cli replacement for ls and tree

https://dystroy.org/broot/documentation/installation/

``` bash
cargo install broot
``` 

### Verbs

`Space` then `verb`

		edit
		create
		view


### Customizing Configuration

https://dystroy.org/broot/documentation/configuration/

`/Users/mertnuhoglu/Library/Preferences/org.dystroy.broot/conf.toml`

``` bash
mkdir -p /Users/mertnuhoglu/projects/private_dotfiles/broot
mv /Users/mertnuhoglu/Library/Preferences/org.dystroy.broot/conf.toml /Users/mertnuhoglu/projects/private_dotfiles/broot
ln -s /Users/mertnuhoglu/projects/private_dotfiles/broot/conf.toml /Users/mertnuhoglu/Library/Preferences/org.dystroy.broot/conf.toml
``` 

### Tricks

Deep fuzzy cd

``` bash
~/projects/study master*
$ dcd brave

~/projects/study/clj/ex/study_clojure/book_clojure_brave master*
``` 

### Usage

Regex

``` bash
/pattern
/pattern/i
``` 

Toggles

``` bash
:sizes
:perm
:h # hidden files
:gi # use .gitignore
:files # just folders
``` 

Quitting

``` bash
^q
:q
``` 

## dust: replace du

https://github.com/bootandy/dust

``` bash
cargo install du-dust
``` 

``` bash
dust
  ##>   66M ─┬ .
  ##>   57M  ├─┬ .config
  ##>   50M  │ ├─┬ yarn
  ##>   50M  │ │ └─┬ global
``` 


## httpie: curl alternative

``` bash
$ tldr http
http

HTTPie: HTTP client, a user-friendly cURL replacement.
More information: <https://httpie.org>.

- Download a URL to a file:
  http -d example.org

- Send form-encoded data:
  http -f example.org name='bob' profile_picture@'bob.png'

- Send JSON object:
  http example.org name='bob'

- Specify an HTTP method:
  http HEAD example.org

- Include an extra header:
  http example.org X-MyHeader:123

- Pass a user name and password for server authentication:
  http -a username:password example.org

- Specify raw request body via `stdin`:
  cat data.txt | http PUT example.org
``` 

# Articles

## Article: A Surprisingly Common Mistake Involving Wildcards & The Find Command

https://blog.robertelder.org/find-command-wildcard-globbing/

Check `~/projects/study/logbook/ex/log_20200209/ex01/main.c`

``` bash
gcc main.c
``` 

``` bash
./a.out *.py
``` 

``` bash
touch foo.py
./a.out *.py
  ##> argc=2
  ##> Arg 0 is: './a.out'
  ##> Arg 1 is: 'foo.py'
``` 

Shell first expands wildcard pattern. Then it passes these expanded names to the program. This is `globbing`

``` bash
man glob
``` 

Lesson: Always quote wildcard chars when used as options for a command:

``` bash
find . -name '*.jpg'
``` 

## Article: An Introduction To Data Science On The Linux Command Line

An Introduction To Data Science On The Linux Command Line

### awk

``` bash
temp,unit
26.1,C
78.1,F
23.1,C
``` 

Convert F to C:

``` bash
cat temps.txt | awk -F',' '{if($2=="F")print (($1-32)*5/9)",C";else print $1","$2}'
``` 

``` bash
temp,unit
26.1,C
25.6111,C
23.1,C
2
``` 

### comm

Common or different lines.

Check `/Users/mertnuhoglu/projects/study/logbook/ex/log_20200209/ex02/a.txt`

``` bash
line0
line1
line3
``` 

Check `/Users/mertnuhoglu/projects/study/logbook/ex/log_20200209/ex02/b.txt`

``` bash
line1
line2
line0
``` 

``` bash
comm -12 a.txt b.txt
  ##> line1
comm -23 a.txt b.txt
  ##> line0
  ##> line3
comm -13 a.txt b.txt
  ##> line2
  ##> line0
``` 

It assumes that input is sorted first.

``` bash
comm -23 <(sort a.txt) <(sort b.txt)
  ##> line3
``` 

### uniq

Check `/Users/mertnuhoglu/projects/study/logbook/ex/log_20200209/ex02/c.csv`

``` bash
Shoes,19.00
Shoes,28.00
Pants,77.00
Socks,12.00
Shirt,22.00
Socks,12.00
Socks,12.00
Boots,82.00
``` 

``` bash
cat c.csv | awk -F',' '{print $1}' | sort | uniq
  ##> Boots
  ##> Pants
  ##> Shirt
  ##> Shoes
  ##> Socks
``` 

Counts of items?

``` bash
cat c.csv | awk -F',' '{print $1}' | sort | uniq -c
  ##>    1 Boots
  ##>    1 Pants
  ##>    1 Shirt
  ##>    2 Shoes
  ##>    3 Socks
``` 

Which are duplicates?

``` bash
cat c.csv | awk -F',' '{print $1}' | sort | uniq -d
  ##> Shoes
  ##> Socks
``` 

### find

Total count of lines in all files:

``` bash
find . -type f -exec cat {} \; | wc -l
``` 

Replace all files:

``` bash
find . -type f -exec sed -i 's/dog/cat/g' {} \;
``` 

### tsort

Topological sort

Check `~/projects/study/logbook/ex/log_20200209/ex02/d.txt`

``` bash
cat d.txt | tsort
  ##> a
  ##> b
  ##> d
  ##> c
  ##> e
cat d.txt | sort -R | tsort
  ##> a
  ##> b
  ##> c
  ##> d
  ##> e
``` 

## Article: Don Libes' Expect: A Surprisingly Underappreciated Unix Automation Tool

https://blog.robertelder.org/don-libes-expect-unix-automation-tool/

### Ex: ls

``` bash
expect -c '
spawn bash
sleep 0.3
send "ls"
interact
exit
'
``` 

#### Logs

##### error: bash spawn edince garip karakterler çıkıyor

``` bash
$ bashNo manual entry for slogin

%}%F{blue}%~%f %F{242}%f %F{cyan}%f %F{yellow}%f
``` 

opt01: prompt customization

``` bash
export PS1=" "
export PS1="$ "
``` 

Çözüm:

`~/.bashrc` dosyasına şunu ekle:

``` bash
export PS1="$ "
``` 

