---
title: "Studying VRP Preparation Codes"
date: 2018-10-11T15:28:05+03:00 
draft: true
description: ""
tags:
categories: javascript, cyclejs, sql
type: post
url:
author: "Mert Nuhoglu"
output:
  html_document:
    css: styles.css
blog: mertnuhoglu.com
resource_files:
- 
path: ~/projects/study/js/vrp/study_vrp.Rmd
state: wip
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

``` {r set-options}
options(width = 150)
options(max.print = 30)
``` 

## 001 study_vrp: concatMap example

``` bash
mkdir -p ex/study_vrp && cd $_ && npm init -y && npm i parcel-bundler --save-dev && npm i xstream @cycle/run @cycle/dom @cycle/http cycle-storageify @cycle/storage @cycle/history @cycle/isolate 
npm i -D babel-cli babel-preset-env
npx tsc --init
``` 

``` bash
cv "plan?select=pln_orl(order_line(purchase_order(purchase_order_id)))"
'## [{"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":1}}}]}, 
'##  {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":1}}}]}, 
'##  {"pln_orl":[]}, 
'##  {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":3}}}]}, 
'##  {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":4}}}, 
'##  {"order_line":{"purchase_order":{"purchase_order_id":2}}}]}]
``` 

Edit `~/projects/study/js/vrp/ex/study_vrp/a001.js`

``` js
as = [{"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":1}}}]}, 
 {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":1}}}]}, 
 {"pln_orl":[]}, 
 {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":3}}}]}, 
 {"pln_orl":[{"order_line":{"purchase_order":{"purchase_order_id":4}}}, 
 {"order_line":{"purchase_order":{"purchase_order_id":2}}}]}]
as.map(a => a.pln_orl.map(b => b.order_line.purchase_order))
``` 

``` js
let ys = as.concatMap(a => a.pln_orl.map(b => b.order_line.purchase_order))
``` 

Run

``` bash
node a001.js
npm run a001 // opt
``` 

Output:

``` js
[ { purchase_order_id: 1 },
  { purchase_order_id: 1 },
  { purchase_order_id: 3 },
  { purchase_order_id: 4 },
  { purchase_order_id: 2 } ]
``` 

## 002 study_vrp: using ramda

Edit `~/projects/study/js/vrp/ex/study_vrp/a002.ts`

``` js
let ys = R.map(a => a.pln_orl.map(b => b.order_line.purchase_order), as)
``` 

Edit `~/projects/study/js/vrp/ex/study_vrp/a003.ts`

``` js
let f = R.pipe(
	R.map(a => a.pln_orl.map(b => b.order_line.purchase_order)),
	R.unnest
)
let ys = f(as)
``` 

Run

``` bash
ts-node a002.js
npm run a002 // opt
``` 

## 003 study_vrp: order_line instead of pln_orl

``` bash
cv "plan?select=order_line(purchase_order(purchase_order_id))&plan_id=eq.1"
'## [{"order_line":[{"purchase_order":{"purchase_order_id":1}}]}]
``` 

Edit `~/projects/study/js/vrp/ex/study_vrp/a004.ts`

``` js
let f = R.pipe(
	R.map(a => a.order_line.map(b => b.purchase_order)),
	R.unnest
)
// [ { purchase_order_id: 1 } ]
``` 

## 005 study_vrp: what if there is no related purchase_order for some plan?

``` bash
cv "plan?select=order_line(purchase_order(purchase_order_id))&plan_id=eq.3"
'## [{"order_line":[]}]
``` 

Edit `~/projects/study/js/vrp/ex/study_vrp/a005.ts`

Edit `~/projects/study/js/vrp/ex/study_vrp/a005e.ts`

``` js
let f = R.pipe(
	R.map(a => R.prop('order_line', a).map(R.prop('purchase_order'))),
	R.unnest
)
let as = [{"order_line":[{"purchase_order":{"purchase_order_id":1}}]}, 
 {"order_line":[{"purchase_order":{"purchase_order_id":1}}]}, 
 {"order_line":[]}, 
 {"order_line":[{"purchase_order":{"purchase_order_id":3}}]}, 
 {"order_line":[{"purchase_order":{"purchase_order_id":4}}, 
 {"purchase_order":{"purchase_order_id":2}}]}]
console.log(f(as))
// [ { purchase_order_id: 1 },
//   { purchase_order_id: 1 },
//   { purchase_order_id: 3 },
//   { purchase_order_id: 4 },
//   { purchase_order_id: 2 } ]
``` 

## 006 study_vrp: cjs sipariş verilerini sunucuya (plumber veya opencpu) gönderir

### 006.01 Prepare curl request

Basic postgrest request:

``` bash
curl -H "Authorization: Bearer $JWT_TOKEN" -H "Content-Type: application/json" -d '[{"company_id": "103", "company_name":"company_103"},{"company_id": "102", "company_name":"company_102"}]'  http://localhost:8080/rest/company
``` 

Basic plumber request to run optimization algorithm in java:

``` bash
curl -v \
	-F sevk_emri_file=@input/20170103/sevk_emri.xlsx \
	-F rate_file=@master/default/rate_optimization.tsv \
	-F planningDate="2017-01-03T00:00:00" \
	-F planId="single_20170103a6" \
	http://localhost:8300/upload_run
``` 

It works. 

Goal: Unify the above requests:

``` bash
curl -v \
	-H "Authorization: Bearer $JWT_TOKEN" \
	-H "Content-Type: application/json" \
	-d '{"sevk_emri_data": [...], "planningDate": "2017-01-03T00:00:00", "planId": "single_20170103a6"}'  \
	http://localhost:8300/post_run
``` 

R code in `~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R`

``` bash
  #' Run
  #' @param sevk_emri_data sevk_emri_data
  #' @param planningDate planningDate
  #' @param planId planId
  #' @param x The number to add
  #' @post /post_run
post_run = function(sevk_emri_data, planningDate, planId) {
``` 

Prepare the data for sevk_emri_data:

		[["irsaliye_no", "irsaliye_sevk_tarihi", "cari_kod", "unvan", "teslIm_adres", "teslim_sehir", "teslim_sehir__1", "malzeme_kodu", "malzeme_adi", "irsaliye_KG", "tesis", "IL", "ILCE", "Yaş/Toz"], ["1043", "2017-01-02T00:00:00Z", ....], ..., ...]

``` bash
curl -v \
	-H "Authorization: Bearer $JWT_TOKEN" \
	-H "Content-Type: application/json" \
	-d '{"sevk_emri_data": [["irsaliye_no", "irsaliye_sevk_tarihi", "cari_kod", "unvan", "teslIm_adres", "teslim_sehir", "teslim_sehir__1", "malzeme_kodu", "malzeme_adi", "irsaliye_KG", "tesis", "IL", "ILCE", "Yaş/Toz"], ["1043", "2017-01-02T00:00:00Z", "2I00048", "ISIKSAN YALITIM INS. TAAH. SAN. VE TIC. LTD. STI.", "FABRIKADAN TESLIM ALACAGIZ.", "TEKİRDAĞ", ], [..], [..]], "planningDate": "2017-01-03T00:00:00", "planId": "single_20170103a6"}'  \
	http://localhost:8300/post_run
``` 

### 006.02 call R post_run from cjs

Edit `/Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/a006_02.js`

``` js
const requests$ = xs.from(
  [
    {
      url: 'http://localhost:8300/post_run',
      method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			send: '{"sevk_emri_data": [["irsaliye_no", "irsaliye_sevk_tarihi", "cari_kod", "unvan", "teslIm_adres", "teslim_sehir", "teslim_sehir__1", "malzeme_kodu", "malzeme_adi", "irsaliye_KG", "tesis", "IL", "ILCE", "Yaş/Toz"], ["1043", "2017-01-02T00:00:00Z", "2I00048", "ISIKSAN YALITIM INS. TAAH. SAN. VE TIC. LTD. STI.", "FABRIKADAN TESLIM ALACAGIZ.", ], ["1044", ], ["1045", ...]], "planningDate": "2017-01-03T00:00:00", "planId": "single_20170103a6"}',
			category: 'express'
    },
  ]
)
``` 

Run:

``` bash
cd /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp
node a006_02.js
``` 

## 007 study_vrp: setup and running the projects v2 id=g_10714

### 007.01: Produce data model: knowledge2yuml id=g_10781

Write the following input files:

		dm/rdb/def/enum_value.xlsx
		dm/rdb/def/enum_var.xlsx
		dm/schema/yuml/datamodel_enum.md
		dm/schema/yuml/datamodel_location.md
		dm/schema/yuml/datamodel_order.md
		dm/schema/yuml/datamodel_shipment.md

Copy them into `yuml2data01` dm folder.

### 007.02 wt_yuml2data01: yuml2data

Description: Generate ddl.sql and sample_data.sql files

Follow `walkthrough yuml2data01 <url:file:///~/projects/itr/itr_documentation/doc_itr.md#r=g_10550>`

``` bash
cd ~/projects/itr/walkthrough_vrp
``` 

Generate the following output files:

		dm/schema/gen/ddl.sql
		dm/schema/gen/views.sql
		dm/sample_data/reset_vrp.sql
		dm/sample_data/sql_insert/sql_insert_enum_value.sql
		dm/sample_data/sql_insert/sql_insert_enum_var.sql

Copy them into actual database such as `vrp_psk01`

### 007.03 Run the database: data2rest

Run database from docker container

Follow `walkthrough vrp_psk01 <url:file:///~/projects/itr/itr_documentation/doc_itr.md#r=g_10551>`

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp_psk01
docker-compose up 
``` 

### 007.04 Run the java, R servers

#### 007.04.01 Setup mongo db [id=#setup_mongo_db] 

Java server has mongo dependency. 

Edit `~/projects/itr/vrp/docker-compose-mongo.yml`

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/
docker-compose -f docker-compose-mongo.yml up -d
docker exec -it vrp_mongo_1 bash
``` 

Create `administrator` user:

``` bash
mongo admin
use admin
db.createUser({ user: "administrator", pwd: '12345', roles: [ { role: "userAdminAnyDatabase", db: "admin" }  ] });
``` 

Create `myUserAdmin` in app db:

``` bash
mongo --port 27017 -u "administrator" -p "12345" --authenticationDatabase "admin"
use beyp_poc
db.createUser({ user: "myUserAdmin", pwd: '12345', roles: ["readWrite"] });
use jtn_poc
db.createUser({ user: "myUserAdmin", pwd: '12345', roles: ["readWrite"] });
``` 

#### 007.04.02 Setup Java

Description: Run Java Algorithm Service

##### 007.04.02a opt01: Java on Localhost

Edit `~/projects/itr/vrp/itr_vrp/config_osx.yml`

``` bash
server:
  applicationConnectors:
    - type: http
      port: 8200
  adminConnectors:
    - type: http
      port: 8201
``` 

Run server:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/itr_vrp/
mvn package && java -jar target/vrp-0.1.jar server config_osx.yml
``` 

##### 007.04.02b opt02: Java on Docker

Edit `~/projects/itr/vrp/itr_vrp/config.yml`

``` bash
server:
  applicationConnectors:
    - type: http
      port: 8080
``` 

Edit `~/projects/itr/vrp/docker-compose3.yml`

``` bash
  algorithm:
    build: ./itr_vrp
    entrypoint:
      - "java"
      - "-jar"
      - "-Done-jar.silent=true"
      - "target/vrp-0.1.jar"
      - "server"
      - "config.yml"
    ports:
      - "8200:8080"
``` 

Run server from docker:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/
docker-compose -f docker-compose3.yml up 
``` 

#### 007.04.03 Setup R Server on Localhost

##### 007.04.03a opt01: R Server with OpenCPU

Run R:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/r/pkg/vrpdata/
R
``` 

``` R
library("devtools")
devtools::load_all()
setenv_osx()
sevk_emri_file = sprintf("%s/input/20170103/sevk_emri.xlsx", Sys.getenv("DATA_DIR"))
rate_file = sprintf("%s/master/default/rate_optimization.tsv", Sys.getenv("DATA_DIR"))
planningDate = "2017-01-03T00:00:00"
planId = "single_20170103a6"
``` 

``` R
> sevk_emri_file
[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/20170103/sevk_emri.xlsx"
> rate_file
[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/master/default/rate_optimization.tsv"
``` 

Run `run_optimization` step by step

``` R
run_optimization <- function(sevk_emri_file, rate_file, planningDate, planId) {
  library(magrittr)
  Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
  sem = rio::import(sevk_emri_file, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))
  rte = rio::import(rate_file)
  folder_name = format(Sys.time(), "%y%m%d_%H%M")
  print(folder_name)
	path_sem = sprintf("%s/input/%s/sevk_emri.xlsx", data_dir(), folder_name)
	dir.create(dirname(path_sem), recursive = T)
  rio::export(sem, path_sem)

  folder_master = "default"
  path_master = sprintf("%s/master/%s", data_dir(), folder_master)
  rio::export(rte, sprintf("%s/rate.tsv", path_master)) # @todo bunu instance klasöründen kullansın java
  prd = rio::import(sprintf("%s/product.tsv", path_master))
  lct = rio::import(sprintf("%s/location.tsv", path_master))
  cmp = rio::import(sprintf("%s/company.tsv", path_master))
  adr = rio::import(sprintf("%s/address.tsv", path_master))
  adv = rio::import(sprintf("%s/address_variant.tsv", path_master))

	sem_tidy = sem %>%
    setNames(c("order_extid", "shipment_date", "company_extid", "company_name", "address", "teslim_sehir", "teslim_ulke", "product_extid", "product_name", "irsaliye_kg", "tesis", "province", "district", "yas_toz")) %>%
    dplyr::mutate(address = stringr::str_trim(address, side = "both")) 

	ord = migrate_order(sem_tidy, cmp)
	orl = migrate_order_line(sem_tidy, ord, prd, lct, adv)

  verify_data(adr, adv, cmp, ord, orl, lct, prd)

	path_ord = sprintf("%s/instance/%s/order.tsv", data_dir(), folder_name)
	path_orl = sprintf("%s/instance/%s/order_line.tsv", data_dir(), folder_name)
	dir.create(dirname(path_ord), recursive = T)

	rio::export(ord, path_ord)
	rio::export(orl, path_orl)
  call_java(instance_dir = folder_name, planningDate = planningDate, planId = planId)
  #call_java(data_dir = "../itr_vrp_data/jtn/", instance_dir = "plan_2017_Q1", planningDate = planningDate, planId = planId)
}

``` 

```	R
> folder_name
[1] "181126_1438"
> path_sem
[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181126_1438/sevk_emri.xlsx"
> path_master
[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/master/default"
> path_ord
[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/instance/181126_1438/order.tsv"
instance_dir = folder_name
planningDate = planningDate
planId = planId
> planningDate
[1] "2017-01-03T00:00:00"
> planId
[1] "single_20170103a6"
``` 

Run `call_java` step by step:

``` R
call_java = function(data_dir = "../data/jtn", master_dir = "default", instance_dir = "default", planningDate = "20170101", planId = "0001") {
  rest_url = sprintf("http://%s/api/main", java_domain())
  r <- httr::GET(rest_url,
           query = list(
             dataDir = data_dir,
             masterDataDir = sprintf("master/%s", master_dir),
             instanceDataDir = sprintf("instance/%s", instance_dir),
             planningDate = planningDate,
             planId = planId
           )
  )
}
``` 

``` R
> rest_url
[1] "http://localhost:8200/api/main"
data_dir = "../data/jtn"
master_dir = "default"
r <- httr::GET(rest_url,
				 query = list(
					 dataDir = data_dir,
					 masterDataDir = sprintf("master/%s", master_dir),
					 instanceDataDir = sprintf("instance/%s", instance_dir),
					 planningDate = planningDate,
					 planId = planId
				 )
)
``` 

###### Error: Empty reply from server

In my first run, I got:

		Empty reply from server

The cause of this error was wrong port settings:

The ports of the Java Algorithm server are set in `config.yml` or `config_osx.yml`:

``` bash
server:
  applicationConnectors:
    - type: http
      port: 8200
  adminConnectors:
    - type: http
      port: 8201
``` 

If you are running inside docker, then you should also define these ports inside `docker-compose.yml`

``` bash
  algorithm:
    build: ./itr_vrp
    entrypoint:
      - "java"
      - "-jar"
      - "-Done-jar.silent=true"
      - "target/vrp-0.1.jar"
      - "server"
      - "config.yml"
    ports:
      - "8200:8080"
``` 

##### 007.04.03b opt02: R Server with Plumber

Run server from docker:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/
docker-compose -f docker-compose3.yml up 
``` 

Install vrpdata library: 

1. Open Rstudio:
2. Open Project: `/Users/mertnuhoglu/projects/itr/vrp/r/pkg/vrpdata/vrpdata.Rproj`
3. Build > Build and Reload

Run R:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/r/pkg/vrpdata/
R
``` 

``` R
Sys.setenv(DATA_DIR = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn")
Sys.setenv(JAVA_DOMAIN = sprintf("%s:%s", "localhost", "8200"))
pr <- plumber::plumb("R/vrp_api.R")
pr$run(port=8300)
``` 

###### opt01: Upload Files using Multipart

Edit `~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R`

``` r
  #' @post /upload_run
upload_run = function(req) {
	folder_name = format(Sys.time(), "%y%m%d_%H%M")
	sevk_emri_file = sprintf("%s/input/%s/sevk_emri.xlsx", data_dir(), folder_name)
	formContents = Rook::Multipart$parse(req)
	print(formContents$sevk_emri_file$tempfile)
	file.move(from = formContents$sevk_emri_file$tempfile, to = sevk_emri_file)
	formContents$rate_file$tempfile
	rate_file = sprintf("%s/input/%s/rate.tsv", data_dir(), folder_name)
	print(formContents$rate_file$tempfile)
	file.move(from = formContents$rate_file$tempfile, to = rate_file)
	planningDate = URLdecode(formContents$planningDate)
	planId = URLdecode(formContents$planId)
	run_optimization(sevk_emri_file, rate_file, planningDate, planId)
}
``` 

Run curl:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/data/jtn
curl -v \
	-F sevk_emri_file=@input/20170103/sevk_emri.xlsx \
	-F rate_file=@master/default/rate_optimization.tsv \
	-F planningDate="2017-01-03T00:00:00" \
	-F planId="single_20170103a6" \
	http://localhost:8300/upload_run
  ##> curl: (52) Empty reply from server
``` 

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/data/jtn
curl -v \
	-F sevk_emri_file=@input/20170103/sevk_emri_small.xlsx \
	-F rate_file=@master/default/rate_optimization.tsv \
	-F planningDate="2017-01-03T00:00:00" \
	-F planId="single_20170103a6" \
	http://localhost:8300/upload_run
``` 

###### opt02: Pass Data as Form Parameters id=g_10719

Edit `~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R`

``` r
  #' Run
  #' @param sevk_emri_data sevk_emri_data
  #' @param planningDate planningDate
  #' @param planId planId
  #' @post /post_run
post_run = function(sevk_emri_data, planningDate, planId) {
  folder_master = "default"
  path_master = sprintf("%s/master/%s", data_dir(), folder_master)
  rate_file = sprintf("%s/rate_base.tsv", path_master) 
	titles = sevk_emri_data[1,]
	sem = dplyr::as_data_frame(sevk_emri_data[2:nrow(sevk_emri_data),]) %>%
		setNames(titles)
	planningDate = "2017-01-03T00:00:00"
	planId = "single_20170103a6"
	folder_name = format(Sys.time(), "%y%m%d_%H%M")
	sevk_emri_file = sprintf("%s/input/%s/sevk_emri.xlsx", data_dir(), folder_name)
	print(sevk_emri_file)
	dir.create(dirname(sevk_emri_file), recursive = T)
	rio::export(sem, sevk_emri_file)
	run_optimization(sevk_emri_file, rate_file, planningDate, planId)
}
``` 

Run curl:

``` bash
~/projects/study/js/vrp/ex/study_vrp/post_run_01/curl_a01.sh
``` 

``` bash
~/projects/study/js/vrp/ex/study_vrp/post_run_01/curl_a02.sh
``` 

###### Error: NPE in Java

This didn't run.

		algorithm_1  | ! java.lang.NullPointerException: null
		algorithm_1  | ! at com.itr.jtn.dat.JnData.getOrderLineFromDb(JnData.java:522)
		algorithm_1  | ! at com.itr.jtn.dat.JnData.getOrderLine(JnData.java:491)
		algorithm_1  | ! at com.itr.jtn.dat.JnData.readOrderLines(JnData.java:270)
		algorithm_1  | ! at com.itr.jtn.dat.JnData.read(JnData.java:75)
		algorithm_1  | ! at com.itr.vrp.alg.GkSolver.populateData(GkSolver.java:87)
		algorithm_1  | ! at com.itr.jtn.main.JnMain.runSolver(JnMain.java:44)
		algorithm_1  | ! at com.itr.beyp.main.RestApi.main(RestApi.java:38)

Let's upload the file using upload_run:

``` bash
curl -v \
	-F sevk_emri_file=@/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181128_1701/sevk_emri.xlsx \
	-F rate_file=@master/default/rate_optimization.tsv \
	-F planningDate="2017-01-03T00:00:00" \
	-F planId="single_20170103a6" \
	http://localhost:8300/upload_run
``` 

This failed too. Let's run the other file:

``` bash
curl -v \
	-F sevk_emri_file=@/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181128_1656/sevk_emri.xlsx \
	-F rate_file=@master/default/rate_optimization.tsv \
	-F planningDate="2017-01-03T00:00:00" \
	-F planId="single_20170103a6" \
	http://localhost:8300/upload_run
``` 

This runs properly. So, the failure must be due to the differences between these files.

Check `~/projects/itr/vrp/data/jtn/instance/181129_1612/order_line.tsv`

		order_line_id	order_id	product_id	address_id	location_id	shipment_date	irsaliye_kg	tesis	yas_toz
		1	1	41	254	28		518	ÇERKEZKÖY	Toz

Cause: shipment_date is empty in 1612 order_line.tsv

This is generated by 

		orl = vrpdata::migrate_order_line(sem_tidy, ord, prd, lct, adv)

Do it step by step on REPL:

``` R
	sevk_emri_file = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181129_1612/sevk_emri.xlsx"
  sem = rio::import(sevk_emri_file, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))
	sem$shipment_date
	##> [1] NA NA NA NA NA
``` 

Why did they all become `NA`?

In Excel, they look like they have the same data. Let's read them as text.

####### opt01: hiç xlsx yazma, hep tsv olarak yaz

######## opt01.03: dosyaları dışarıdan xlsx ve tsv olarak okuyup karşılaştır

``` R
semf_1648 = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181129_1648/sevk_emri.tsv"
semf_1613 = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/181129_1613/sevk_emri.xlsx"
sem_1648 = rio::import(semf_1648)
sem_1613 = rio::import(semf_1613, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))
folder_name_1648 = basename(dirname(semf_1648))
folder_name_1613 = basename(dirname(semf_1613))
``` 

``` R
> sem_1648$shipment_date %>% str
 chr [1:5] "2017/01/03 03:00:00" "2017/01/03 03:00:00" "2017/01/03 03:00:00" "2017/01/03 03:00:00" "2017/01/03 03:00:00"
sem_1613$shipment_date %>% str
> sem_1613$shipment_date %>% str
 POSIXct[1:5], format: "2017-01-03 03:00:00" "2017-01-03 03:00:00" "2017-01-03 03:00:00" "2017-01-03 03:00:00" "2017-01-03 03:00:00"
``` 

Check if there are other differences too:

``` bash
library(compare)
compare(sem_1613, sem_1648, allowAll=TRUE)
  ##> FALSE [TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE]
  ##>   [order_extid] coerced from <integer> to <character>
  ##>   [shipment_date] No comparison available between <POSIXct> and <character>
  ##>   [shipment_date] No comparison available between <POSIXt> and <character>
  ##>   [irsaliye_kg] coerced from <integer> to <numeric>
  ##>   [shipment_date] No comparison available between <POSIXct> and <character>
  ##>   [shipment_date] No comparison available between <POSIXt> and <character>
  ##>   [shipment_date] No comparison available between <POSIXct> and <character>
  ##>   [shipment_date] No comparison available between <POSIXt> and <character>
  ##>   [shipment_date] dropped attributes
  ##>   [address] ignored case
  ##>   [teslim_sehir] ignored case
``` 

Now let's run migrate functions and see the differences of the resulting files:

``` r
	rate_file = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/master/default/rate_optimization.tsv"
  Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
  rte = rio::import(rate_file)
	folder_name = basename(dirname(sevk_emri_file))

  folder_master = "default"
  path_master = sprintf("%s/master/%s", vrpdata::data_dir(), folder_master)
  prd = rio::import(sprintf("%s/product.tsv", path_master))
  lct = rio::import(sprintf("%s/location.tsv", path_master))
  cmp = rio::import(sprintf("%s/company.tsv", path_master))
  adr = rio::import(sprintf("%s/address.tsv", path_master))
  adv = rio::import(sprintf("%s/address_variant.tsv", path_master))

	sem_tidy = sem %>%
    setNames(c("order_extid", "shipment_date", "company_extid", "company_name", "address", "teslim_sehir", "teslim_ulke", "product_extid", "product_name", "irsaliye_kg", "tesis", "province", "district", "yas_toz")) %>%
    dplyr::mutate(address = stringr::str_trim(address, side = "both")) 

	ord = vrpdata::migrate_order(sem_tidy, cmp)
	orl = vrpdata::migrate_order_line(sem_tidy, ord, prd, lct, adv)
``` 

Get the resulting files:

``` bash
	path_ord = sprintf("%s/instance/%s/order.tsv", vrpdata::data_dir(), folder_name)
	path_orl = sprintf("%s/instance/%s/order_line.tsv", vrpdata::data_dir(), folder_name)
	dir.create(dirname(path_ord), recursive = T)

	rio::export(ord, path_ord)
	rio::export(orl, path_orl)
``` 

Run the above code chunk with the following parameters one after the other:

``` r
sevk_emri_file = semf_1648
sevk_emri_file = semf_1613
sevk_emri_file = semf_1612
``` 

Store the results at the end:

``` r
orl_1648 = orl
orl_1613 = orl
``` 

Check differences:

``` r
compare(orl_1648, orl_1613, allowAll=TRUE)
  ##> TRUE
all.equal(orl_1648, orl_1613)
  ##> TRUE
identical(orl_1648, orl_1613)
  ##> TRUE
``` 

Since the migrated files are the same, then java should handle them equally too:

``` r
	planningDate = "2017-01-03T00:00:00"
	planId = "single_20170103a6"
  vrpdata::call_java(instance_dir = folder_name_1648, planningDate = planningDate, planId = planId)
	##> NPE
  vrpdata::call_java(instance_dir = folder_name_1613, planningDate = planningDate, planId = planId)
	##> NPE
``` 

Note that, shipment_date is NA:

``` r
> orl_1648$shipment_date
[1] NA NA NA NA NA
``` 


###### Error: empty reply from server

I got the following error from curl:

		empty reply from server

opt01: -H

		curl -v \
			-H "Content-Type: application/json" \
			-F sevk_emri_file=@input/20170103/sevk_emri.xlsx \
			-F rate_file=@master/default/rate_optimization.tsv \
			-F planningDate="2017-01-03T00:00:00" \
			-F planId="single_20170103a6" \
			http://localhost:8300/upload_run

opt02: Return anything

		call_java = function(...) {
			return(list(planId = planId))

This worked.

opt03: docker listens to port 8300 too

``` bash
lsof -n -i -P | rg 8300
	##> docker
``` 

###### Error: java.time.format.DateTimeParseException: Text '2017-01-03T00%3A00%3A00' could not be parsed at index 13

I got this error when I did:

		upload_run = function(req) {
			...
			planningDate = formContents$planningDate
			planId = formContents$planId
			#planningDate = "2017-01-03T00:00:00"
			#planId = "single_20170103a6"

R should decode the coming request data `'2017-01-03T00%3A00%3A00'` and pass it as `'2017-01-03T00:00:00'` to java.

Fix:

			planningDate = URLdecode(formContents$planningDate)
			planId = URLdecode(formContents$planId)

###### Error: could not find function \"%>%\"

I got this error when I called:

		curl ...  http://localhost:8300/post_run

Message:

		{"error":["500 - Internal server error"],"message":["Error in dplyr::as_data_frame(sevk_emri_data[2:nrow(sevk_emri_data), ]) %>% : could not find function \"%>%\"\n"]}

Fix:

		post_run = function(sevk_emri_data, planningDate, planId) {
			library(magrittr)

###### Error: Error in fread(dec = ".", col_types = c("text",...)

I got this error when I called:

		curl ...  http://localhost:8300/post_run

Message:

		{"error":["500 - Internal server error"],"message":["Error in fread(dec = \".\", col_types = c(\"text\", \"date\", \"text\", \"text\", : unused argument (col_types = c(\"text\", \"date\", \"text\", \"text\", \"text\", \"text\", \"text\", \"text\", \"text\", \"numeric\", \"text\", \"text\", \"text\", \"text\"))\n"]}

####### opt01: run post_run in R

In curl, we pass this data in format:

		-d '{"sevk_emri_data": [["irsaliye_no", "irsaliye_sevk_tarihi", "cari_kod", "unvan", "teslIm_adres", "teslim_sehir", "teslim_sehir__1", "malzeme_kodu", "malzeme_adi", "irsaliye_KG", "tesis", "IL", "ILCE", "Yaş/Toz"], ["1043", "2017-01-02T00:00:00Z", "2I00048", "ISIKSAN YALITIM INS. TAAH. SAN. VE TIC. LTD. STI.", "FABRIKADAN TESLIM ALACAGIZ.", "TEKİRDAĞ", "TÜRKİYE", "1032248PX20", "PE 5088 RAL3004 Smooth", "20", "ÇERKEZKÖY", "TEKIRDAG", "CERKEZKOY", "Toz"], ["1044", "2017-01-02T00:00:00Z", "1P00009", "BSH EV ALETLERI SANAYI VE TICARET A.S.", "YILDIRIM BEYAZID MAH.HAYRI BATUR CAD. NO: 72 CERKEZKOY", "TEKİRDAĞ", "TÜRKİYE", "1021378EB500", "G Miles+ W87 Vzf 07020 Smooth", "1000", "ÇERKEZKÖY", "TEKIRDAG", "CERKEZKOY", "Toz"], ["1045", "2017-01-02T00:00:00Z", "1P00009", "BSH EV ALETLERI SANAYI VE TICARET A.S.", "YILDIRIM BEYAZID MAH.HAYRI BATUR CAD. NO: 72 CERKEZKOY", "TEKİRDAĞ", "TÜRKİYE", "1023813EB300", "G Miles+ W88 Vzf 07020 Smooth", "300", "ÇERKEZKÖY", "TEKIRDAG", "CERKEZKOY", "Toz"]], "planningDate": "2017-01-03T00:00:00", "planId": "single_20170103a6"}'  \

How can we test this data in R directly?

We expect that `sevk_emri_data` is of type `data.frame`

		sevk_emri_data[1,]

How to convert string into data.frame?

- `read.table`
- `fread`
- `read.delim` 

Copy the data from excel file: `input/20170103/sevk_emri.xlsx`

Edit `~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R`

``` R
data = '"order_extid"	"shipment_date"	"company_extid"	"company_name"	"address"	"teslim_sehir"	"teslim_ulke"	"product_extid"	"product_name"	"irsaliye_kg"	"tesis"	"province"	"district"	"yas_toz"
"1070"	2017-01-03 03:00:00	"2D00026"	"DOGUS SANAYI KIMYASALLARI TIC LTD STI.          (IND)"	"MERAY STATIK   BUSAN SAN. FEVZI  CAKMAK MAH . 10646 SOK. NO:13 KARATAY /KONYA"	"ANKARA"	"TÜRKİYE"	"1036659PX20"	"GC K03T RAL9016 Smooth"	80	"ÇERKEZKÖY"	"KONYA"	"KARATAY"	"Toz"
"1071"	2017-01-03 03:00:00	"2E+85"	"END CELIK KIMYA MAKINA PLASTIK TEKSTIL SAN.TIC. LTD. STI."	"TUNA ALUMINYUM METAL KIMYA INS.SAN.VE DIS.TIC.A.S. VELIKOY ORG.SAN.BOLG. SANAYI BULVARI NO:98/A CERKEZKOY TEKIRDAG"	NA	"TÜRKİYE"	"1036383PX20"	"PE 5088 White Smooth"	300	"ÇERKEZKÖY"	"TEKIRDAG"	"CERKEZKOY"	"Toz"
"1072"	2017-01-03 03:00:00	"2I00048"	"ISIKSAN YALITIM INS. TAAH. SAN. VE TIC. LTD. STI."	"IRTEM TARIM MAKINALARI SAN.VE TIC.LTD.STI.- OSB CELIK SOK.NO:3/5 HAYRABOLU/TEKIRDAG"	"TEKİRDAĞ"	"TÜRKİYE"	"1040346PX20"	"PE 5068 RAL3000 Smooth"	1040	"ÇERKEZKÖY"	"TEKIRDAG"	"HAYRABOLU"	"Toz"'
sevk_emri_data = read.delim(text = data, header = TRUE)
planningDate = "2017-01-03T00:00:00"
planId = "single_20170103a6"
``` 

Run `post_run`

``` R
Sys.setenv(DATA_DIR = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn")
Sys.setenv(JAVA_DOMAIN = sprintf("%s:%s", "localhost", "8200"))
source("~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R")
source("~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R")
post_run(sevk_emri_data, planningDate, planId)
``` 

I get the same error:

		Error in fread(dec = ".", col_types = c("text", "date", "text", "text",  :
			unused argument (col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))

Run `post_run` step by step

``` R
  # ... run each line in terminal
sevk_emri_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/../../../data/jtn/input/190110_0024/sevk_emri.tsv"
rate_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/../../../data/jtn/master/default/rate_base.tsv"
run_optimization(sevk_emri_file, rate_file, planningDate, planId)
``` 

Same error with better stacktrace:

		3: rio::import(sevk_emri_file, col_types = c("text", "date", "text",
					 "text", "text", "text", "text", "text", "text", "numeric",
				... at vrp_api.R#184

This is that line:

		sem = rio::import(sevk_emri_file, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))

Why does it not give this error with `upload_run`?

		curl -v \
			-H "Content-Type: application/json" \
			-F sevk_emri_file=@input/20170103/sevk_emri.xlsx \
			-F rate_file=@master/default/rate_optimization.tsv \
			-F planningDate="2017-01-03T00:00:00" \
			-F planId="single_20170103a6" \
			http://localhost:8300/upload_run

Call this service directly on R side as well. 

First setup the arguments of `upload_run`:

``` R
formContents = list( 
	sevk_emri_file = list( tempfile = "input/20170103/sevk_emri.xlsx" ),
	rate_file = list( tempfile = "master/default/rate_optimization.tsv" ),
	planningDate = "2017-01-03T00:00:00",
	planId = "single_20170103a6"
)
``` 

Run `upload_run` step by step

``` R
  # ... run each line in terminal
sevk_emri_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_0034/sevk_emri.xlsx"
rate_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_0034/rate.tsv"
run_optimization(sevk_emri_file, rate_file, planningDate, planId)
``` 

Problem line:

		sem = rio::import(sevk_emri_file, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))

This one works without error. So, now we are sure that the problem lies between the difference in the following files:

		"/Users/mertnuhoglu/projects/itr/vrp/data/jtn/../../../data/jtn/input/190110_0024/sevk_emri.tsv"
		"/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_0034/sevk_emri.xlsx"

Let's open `~/projects/itr/data/jtn/input/190110_0024/sevk_emri.tsv`

		1070	1	1	1	2	1	1	2	1	80	1	1	3	1

So, the cause of the problem is clear now. This is not the data we passed to `post_run` in first step.

####### Why is sevk_emri data broken?

Run the code step by step in R again:

``` R
source("~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R")
``` 

Follow `sevk_emri_data` inside `post_run`

``` R
	titles = sevk_emri_data[1,]
	sem = dplyr::as_data_frame(sevk_emri_data[2:nrow(sevk_emri_data),]) %>%
		setNames(titles)
	str(sem)
  ##> Classes ‘tbl_df’, ‘tbl’ and 'data.frame':       2 obs. of  14 variables:
  ##>  $ 1070: int  1071 1072
  ##>  $ 1   : Factor w/ 1 level "2017-01-03 03:00:00": 1 1
  ##>  $ 1   : Factor w/ 3 levels "2D00026","2E+85",..: 2 3
``` 

So, the problem occurs here. Check `sevk_emri_data` too:

``` R
str(sevk_emri_data)
  ##> 'data.frame':   3 obs. of  14 variables:
  ##>  $ order_extid  : int  1070 1071 1072
  ##>  $ shipment_date: Factor w/ 1 level "2017-01-03 03:00:00": 1 1 1
  ##>  $ company_extid: Factor w/ 3 levels "2D00026","2E+85",..: 1 2 3
``` 

Change this

		sevk_emri_data = read.delim(text = data, header = TRUE)

to:

		sevk_emri_data = read.delim(text = data, header = TRUE, stringsAsFactors = F)

Remove `sem` altogether. We don't need to convert `data.frame` to `data_frame`

Run `post_run` step by step again.

Check `/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_0107/sevk_emri.tsv`

``` R
...
sevk_emri_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_0107/sevk_emri.tsv"
sem = rio::import(sevk_emri_file, col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))
``` 

We still get this error:

		Error in fread(dec = ".", col_types = c("text", "date", "text", "text",  :
		unused argument (col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "text", "text", "text"))

Remove `col_types`

``` R
sem = rio::import(sevk_emri_file)
``` 

Now, it works. 

Then we need to refactor `run_optimization`

Find the type of the file.

``` R
source("~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R")
source("~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R")
post_run(sevk_emri_data, planningDate, planId)
``` 

Now, it works. 

###### Error: <assertError: is_empty(x = instances_with_no_attribute_value) is not TRUE> id=g_10754

Where does this error occur?

####### opt01: Systematic elimination of options

In R side delete lines one by one and call curl again.

		#call_java(instance_dir = folder_name, planningDate = planningDate, planId = planId)

Same error

		#run_optimization(sevk_emri_file, rate_file, planningDate, planId)

No error

So, the error occurs somewhere in `run_optimization`

		#vrpdata::verify_data(adr, adv, cmp, ord, orl, lct, prd)

This is where the error occurs.

opt01: 

Convert it to:

		verify_data(adr, adv, cmp, ord, orl, lct, prd)

Source its definition:

		source("~/projects/itr/vrp/r/pkg/vrpdata/R/verify.R")

opt02: Reload vrpdata library

Rstudio > Build and Reload Library

Run the plumber server inside Rstudio

Which verification does fail inside `verify_data`?

Why does `assert_non_na` not print exact file name?

		print(sprintf("assert_non_na: %s", fn))

The file is here:

		/Users/mertnuhoglu/projects/itr/vrp/data/jtn/verify/default/assert_non_na_Order$company_id.tsv

		order_id	order_extid	company_extid	company_id
		1	order_extid	company_extid	

So, the error occurs here:

		assert_non_na(ord, "company_id", filename = "Order$company_id")

This shows that company_id is empty for order_id = 1. Why?

`ord` comes from here:

		ord = vrpdata::migrate_order(sem_tidy, cmp)

####### Why is `order$company_id` empty?

opt01: Debug step by step from R:

``` R
source("~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R")
``` 

Run each line in `post_run`

``` R
sevk_emri_file
  ##> [1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1218/sevk_emri.tsv"
``` 

Run each line in `run_optimization`

``` R
ord
  ##>   order_id order_extid company_extid company_id
  ##> 1        1        1070       2D00026          9
  ##> 2        2        1071         2E+85         16
  ##> 3        3        1072       2I00048          1
``` 

Weird, this has no empty company_id here. 

All verifications pass here. 

######## Compare sevk_emri_file between R run and curl run:

R run produced this file:

		/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1218/sevk_emri.tsv

curl run produced this file:

		/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1226/sevk_emri.tsv

They are totally different files. How come this occur?

####### Why are sevk_emri_file between R and curl runs different?

This is curl call:

``` bash
$ curl -v \
        -H "Content-Type: application/json" \
        -d '{"sevk_emri_data": [["order_extid", ...], ["1081", "2017/01/03 03:00:00", "2B00079", "BUYUKASIK MIMARLIK TAS.VE YAPI MALZ.LTD.STI. (IND)", "ADANA DEPO", ...}'  \
        http://localhost:8300/post_run
``` 

This input data is different than R call given in `~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R`

Make curl call's input data the same as here. 

####### Solution: new curl command:

How do we convert tsv data into json?

Use: https://codebeautify.org/tsv-to-json-converter

opt: Use Vim command: ConvertTsv2Json (worse)

New curl command is in `~/projects/study/js/vrp/ex/study_vrp/post_run_01/curl01.sh`

###### Error: Why does curl run produce additional header line in sevk_emri.tsv file?

Now, curl run produced this file:

		/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1244/sevk_emri.tsv

It still has an additional header line

		V1	V2	V3	V4	V5	V6	V7	V8	V9	V10	V11	V12	V13	V14

opt01: Use write.table instead of rio::export

		readr::write_tsv(sevk_emri_data, sevk_emri_file, na = "")

###### Error: is.data.frame(x) is not TRUE

		{"error":["500 - Internal server error"],"message":["Error: is.data.frame(x) is not TRUE\n"]}

Check tsv file:

		/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1302/sevk_emri.tsv

sevk_emri_data is read as `matrix.` We need to convert it to `data.frame`:

		titles = sevk_emri_data[1,]
		sem = dplyr::as_data_frame(sevk_emri_data[2:nrow(sevk_emri_data),]) %>%
			setNames(titles)
 
Check tsv file:

		[1] "/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/190110_1420/sevk_emri.tsv"

### 007.05 Call post_run with big data from curl id=g_10757

Description: Upload big data 

#### Normal case:

``` bash
sh /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/post_run_01/curl01.sh
``` 

Pass data as json file:

``` bash
sh /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/post_run_01/curl03.sh
``` 

Here we pass data to curl using:

		-d '@data.json'  \

It works too.

Now, pass big data from `/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/20170103/sevk_emri.json`

		--data '@/Users/mertnuhoglu/projects/itr/vrp/data/jtn/input/20170103/sevk_emri.json'  \

Run it:

``` bash
sh /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/post_run_01/curl02.sh
``` 

#### Error: in (function (sevk_emri_data, planningDate, planId) : argument \"sevk_emri_data\" is missing, with no default\n"]}

I forgot to add the other parameters into `sevk_emri.json`

		, "planningDate": "2017-01-03T00:00:00"
		, "planId": "single_20170103a6"

#### Error: assert "assert_non_na: /Users/mertnuhoglu/projects/itr/vrp/data/jtn/verify/default/assert_non_na_Order$company_id.tsv"

No company_id for two rows:

		order_id	order_extid	company_extid	company_id
		1	1071	20000000000000000292613904613497460619400859757293101185572215743395927285022964318208	
		4	1074	20000000000000000292613904613497460619400859757293101185572215743395927285022964318208	

Cause, their company_id in json file is not quoted:

      2e+85,

Wrap it with quotes:

      "2e+85",

``` bash
cd /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/post_run_01/
sh curl02.sh
``` 

Still the same error.

Remove these rows.

Now, it works.

End result:

		com.itr.vrp.eng.GkOutpEngine: Solution written to : plan_single_20170103a6.xlsx

Output: `/Users/mertnuhoglu/projects/itr/vrp/data/jtn/out/plan_single_20170103a6.xlsx`

### 007.06 Summary: Run post_run: input2plan 

Description: Run Optimization: Upload Data to R and Java and produce optimized plan.

Type: input/sevk_emri.json -> out/plan.xlsx

Module: vrpdata::post_run

#### 007.06.01 opt01: Call from curl id=g_10753

Step 01: Setup mongo db as described in [007.04.01 Setup mongo db](#setup_mongo_db)

Step 02: Run vrp server from docker:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/
docker-compose -f /Users/mertnuhoglu/projects/itr/vrp/docker-compose3.yml up 
``` 

Step 03: Run R plumber server:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/r/pkg/vrpdata/
R
``` 

``` R
Sys.setenv(DATA_DIR = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn")
Sys.setenv(JAVA_DOMAIN = sprintf("%s:%s", "localhost", "8200"))
pr <- plumber::plumb("R/vrp_api.R")
pr$run(port=8300)
``` 

Step 04: Test it

Upload the data to R server. It will call optimization algorithm in java side. 

Run curl command: `~/projects/study/js/vrp/ex/study_vrp/post_run_01/curl01.sh`

Run curl command with big data: `~/projects/study/js/vrp/ex/study_vrp/post_run_01/curl02.sh`

``` bash
sh /Users/mertnuhoglu/projects/study/js/vrp/ex/study_vrp/post_run_01/curl02.sh
``` 

Output: `/Users/mertnuhoglu/projects/itr/vrp/data/jtn/out/plan_single_20170103a6.xlsx`

#### 007.06.02 opt02: Call within R id=g_10755

Description: Running R Services in R Console 

Step 01: Setup context

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/
docker-compose -f docker-compose3.yml up 
``` 

Open an R console:

``` bash
cd /Users/mertnuhoglu/projects/itr/vrp/data/jtn
``` 

``` R
Sys.setenv(DATA_DIR = "/Users/mertnuhoglu/projects/itr/vrp/data/jtn")
Sys.setenv(JAVA_DOMAIN = sprintf("%s:%s", "localhost", "8200"))
source("~/projects/itr/vrp/r/pkg/vrpdata/R/vrp_api.R")
``` 

Step 02.a: Run `post_run`

Edit `~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R`

Copy the data from excel file: `input/20170103/sevk_emri.xlsx`

Edit `~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R`

``` R
data = '"order_extid"	"shipment_date"	"company_extid"	"company_name"	"address"	"teslim_sehir"	"teslim_ulke"	"product_extid"	"product_name"	"irsaliye_kg"	"tesis"	"province"	"district"	"yas_toz"
"1070"	2017-01-03 03:00:00	"2D00026"	"DOGUS SANAYI KIMYASALLARI TIC LTD STI.          (IND)"	"MERAY STATIK   BUSAN SAN. FEVZI  CAKMAK MAH . 10646 SOK. NO:13 KARATAY /KONYA"	"ANKARA"	"TÜRKİYE"	"1036659PX20"	"GC K03T RAL9016 Smooth"	80	"ÇERKEZKÖY"	"KONYA"	"KARATAY"	"Toz"
"1071"	2017-01-03 03:00:00	"2E+85"	"END CELIK KIMYA MAKINA PLASTIK TEKSTIL SAN.TIC. LTD. STI."	"TUNA ALUMINYUM METAL KIMYA INS.SAN.VE DIS.TIC.A.S. VELIKOY ORG.SAN.BOLG. SANAYI BULVARI NO:98/A CERKEZKOY TEKIRDAG"	NA	"TÜRKİYE"	"1036383PX20"	"PE 5088 White Smooth"	300	"ÇERKEZKÖY"	"TEKIRDAG"	"CERKEZKOY"	"Toz"
"1072"	2017-01-03 03:00:00	"2I00048"	"ISIKSAN YALITIM INS. TAAH. SAN. VE TIC. LTD. STI."	"IRTEM TARIM MAKINALARI SAN.VE TIC.LTD.STI.- OSB CELIK SOK.NO:3/5 HAYRABOLU/TEKIRDAG"	"TEKİRDAĞ"	"TÜRKİYE"	"1040346PX20"	"PE 5068 RAL3000 Smooth"	1040	"ÇERKEZKÖY"	"TEKIRDAG"	"HAYRABOLU"	"Toz"'
sevk_emri_data = read.delim(text = data, header = TRUE)
planningDate = "2017-01-03T00:00:00"
planId = "single_20170103a6"
``` 

``` R
source("~/projects/study/js/vrp/ex/study_vrp/post_run_01/data.R")
post_run(sevk_emri_data, planningDate, planId)
``` 

Step 02.b: Run `upload_run`

First prepare the arguments of `upload_run`:

``` R
formContents = list( 
	sevk_emri_file = list( tempfile = "input/20170103/sevk_emri.xlsx" ),
	rate_file = list( tempfile = "master/default/rate_optimization.tsv" ),
	planningDate = "2017-01-03T00:00:00",
	planId = "single_20170103a6"
)
``` 

Run `upload_run` step by step

## 008 flow02.01: Frontend sends the data to backend

According to `flow02.01: 5. cjs bu datayı sunucuya gönderir <url:file:///~/projects/itr/itr_documentation/doc_itr.md#r=g_10778>`

		5.1. cjs, sem.xlsx dosyasını submit eder (vrp_api::post_run() fonksiyonunu çağırır)
		5.2. R, DB'den master verilerini çeker: rate, product, location, company, address, address_variant
		5.3. R, bu master verilerini bir klasöre kaydeder `default`
		5.4. R, sem.xlsx'ten oluşturduğu ord, orl verilerine `run_id` ekler
		5.5. R, ord ve orl verilerini DB'ye kaydeder
		5.6. R, master verilerin archive kopyalarını oluşturur. 
			Bunlara run_id ekler
			Bunları da DB'ye kaydeder
		5.7. R, java servisini çağırır (vrp_api::call_java())

### 008.01 Add `run_id` to all data files id=g_10779

By flowcase step 5.6, we will add `run_id` to all data files and we will run `call_java()`

#### 008.01.01 Test if `run_id` column works in Java side

###### 008.01.01.01 Existing java call and files

Take an existing working java call:

		-> GET /api/main?dataDir=..%2Fdata%2Fjtn&masterDataDir=master%2Fdefault&instanceDataDir=instance%2F190122_2158&planningDate=2017-01-03T00%3A00%3A00&planId=single_20170103a6 HTTP/1.1

Instance input files:

		~/projects/itr/vrp/data/jtn/instance/190122_2158/order.tsv
		~/projects/itr/vrp/data/jtn/instance/190122_2158/order_line.tsv

Master input files:

		~/projects/itr/vrp/data/jtn/master/default/rate.tsv
		address.tsv
		address_variant.tsv
		administrative_location.tsv
		audit.tsv
		company.tsv*
		location.tsv*
		merkez_ilce.tsv
		product.tsv
		rate.tsv

###### 008.01.01.02 Create new files with `run_id`

``` bash
mkdir -p ~/projects/itr/vrp/data/jtn/instance/test_run_id01/
mkdir -p ~/projects/itr/vrp/data/jtn/master/test_run_id01/
``` 

``` R
library(dplyr)
rio::import("~/projects/itr/vrp/data/jtn/instance/190122_2158/order.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/instance/test_run_id01/order.tsv")
rio::import("~/projects/itr/vrp/data/jtn/instance/190122_2158/order_line.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/instance/test_run_id01/order_line.tsv")
rio::import("~/projects/itr/vrp/data/jtn/master/default/rate.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/master/test_run_id01/rate.tsv")
rio::import("~/projects/itr/vrp/data/jtn/master/default/company.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/master/test_run_id01/company.tsv")
rio::import("~/projects/itr/vrp/data/jtn/master/default/location.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/master/test_run_id01/location.tsv")
rio::import("~/projects/itr/vrp/data/jtn/master/default/product.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/master/test_run_id01/product.tsv")
rio::import("~/projects/itr/vrp/data/jtn/master/default/merkez_ilce.tsv") %>%
	mutate(run_id = "test_run_id01") %>%
	rio::export("~/projects/itr/vrp/data/jtn/master/test_run_id01/merkez_ilce.tsv")
``` 

###### 008.01.01.03 Call java service using curl

``` bash
curl http://localhost:8200/api/main?dataDir=..%2Fdata%2Fjtn&masterDataDir=master%2Ftest_run_id01&instanceDataDir=instance%2Ftest_run_id01&planningDate=2017-01-03T00%3A00%3A00&planId=single_20170103a7_test_run_id01
``` 

### 008.02 Store instance data in database id=g_10780

By flowcase step 5.6, we will store instance data to database.

#### 008.02.01 Update database schema: Add `run_id` to all tables

#### 008.02.02 Test importing data to postgrest using curl

``` bash
curl -H "Authorization: Bearer $JWT_TOKEN" -H "Content-Type: text/csv" --data-binary @/Users/mertnuhoglu/projects/study/db/ex/study_postgrest/e01/company01.csv http://localhost:8080/rest/company
``` 



