---
title: "studying linear regression: sejohnston code"
date: 2019-11-06T16:51:52+03:00 
draft: true
description: ""
tags:
categories: r statistics
type: post
url:
author: "Mert Nuhoglu"
output: rmarkdown::html_document

---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

``` {r include=F}
options(width = 150)
options(max.print = 30)
options(scipen = 999)
``` 

Code from: https://sejohnston.com/2012/08/09/a-quick-and-easy-function-to-plot-lm-results-in-r/

``` {R echo = F, message = F, warning = F}
library(ggplot2)
library(dplyr)
``` 

``` {r}
data(iris)
head(iris)
``` 

Linear regression of Sepal.Length depending on Petal.Width:

``` {r}
fit1 <- lm(Sepal.Length ~ Petal.Width, data = iris)
summary(fit1)
``` 

Visualization of linear regression data fitting:

``` {r}
plot(Sepal.Length ~ Petal.Width, data = iris)
abline(fit1)
``` 

Same visualization with ggplot2

``` {r}
library(ggplot2)

ggplot(iris, aes(x = Petal.Width, y = Sepal.Length)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")
``` 

Show important statistics on top of graph:

``` {r}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
fit1 <- lm(Sepal.Length ~ Petal.Width, data = iris)
ggplotRegression(fit1)
``` 

