-- df enum_value_id: word=./data/ddl_to_data_enum_value_id.txt
CREATE TABLE enum_value (
  enum_value_id INT PRIMARY KEY
  -- df: text=enum_value_id length=1 
  ) ;
CREATE TABLE place ( --df: mult=2.0
  place_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,  enum_value_id INT  REFERENCES enum_value (enum_value_id)
  -- df: text=enum_value_id length=1 
  ,  address TEXT 
  ) ;


