
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table enum_value (5)
\echo # filling table enum_value (5)
COPY enum_value (enum_value_id) FROM STDIN (ENCODING 'utf-8');
3000
3001
3002
3000
3001
\.

-- fill table place (10)
\echo # filling table place (10)
COPY place (place_id,place_enum,address,action_enum) FROM STDIN (ENCODING 'utf-8');
1	3002	address_10	2001
2	3001	address_4_	2001
3	\N	address_3_3_3	2000
4	3000	address_6_6_6	2001
5	\N	address_3_3_3	2001
6	3000	address_2_2_2_2_	2001
7	3002	address_7_	2001
8	3001	address_2_2_2_2_	2001
9	3000	address_2_2_2_2_	2000
10	3001	address_5_5_5_5_	2000
\.

-- restart sequences

-- analyze modified tables
ANALYZE enum_value;
ANALYZE place;
