
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table order_line (2)
\echo # filling table order_line (2)
COPY order_line (order_line_id,purchase_order_id) FROM STDIN (ENCODING 'utf-8');
1	purchase
2	purchase
\.

-- fill table plan (2)
\echo # filling table plan (2)
COPY plan (plan_id,title) FROM STDIN (ENCODING 'utf-8');
plan_id_2_2_2_2_	title_2_2_2_2_2_
plan_id_1_	title_1_1_1_
\.

-- fill table pln_orl (4)
\echo # filling table pln_orl (4)
COPY pln_orl (plan_id,order_line_id) FROM STDIN (ENCODING 'utf-8');
plan_id_4_	1
plan_id_2_2_2_2_	1
plan_id_4_	2
plan_id_1_	1
\.

-- restart sequences

-- analyze modified tables
ANALYZE order_line;
ANALYZE plan;
ANALYZE pln_orl;
