
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table order_line (2)
\echo # filling table order_line (2)
COPY order_line (order_line_id,shipment_date,irsaliye_kg,tesis,yas_toz) FROM STDIN (ENCODING 'utf-8');
1	2018-01-26 13:03:30	irsaliye_kg_2_	tesis_1_	FALSE
2	2018-01-26 13:03:30	irsaliye_k	tesis_1_	FALSE
\.

-- fill table plan (2)
\echo # filling table plan (2)
COPY plan (plan_id,title) FROM STDIN (ENCODING 'utf-8');
1	title_1_1_1_
2	title_1_1_1_
\.

-- fill table pln_orl (4)
\echo # filling table pln_orl (4)
COPY pln_orl (plan_id,order_line_id) FROM STDIN (ENCODING 'utf-8');
1	2
1	1
2	2
1	2
\.

-- restart sequences

-- analyze modified tables
ANALYZE order_line;
ANALYZE plan;
ANALYZE pln_orl;
