
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table enum_value (5)
\echo # filling table enum_value (5)
COPY enum_value (enum_value_id) FROM STDIN (ENCODING 'utf-8');
1000
1001
1002
1003
1004
\.

-- fill table place (10)
\echo # filling table place (10)
COPY place (place_id,enum_value_id,address) FROM STDIN (ENCODING 'utf-8');
1	1004	address_8_8_8_8_
2	1001	address_5_5_5_5_
3	1001	address_8_8_8_8_
4	1001	address_1_
5	1000	address_4_
6	1004	address_1_
7	1002	address_1_
8	1005	address_7_
9	1002	address_4_
10	1003	address_10
\.

-- restart sequences

-- analyze modified tables
ANALYZE enum_value;
ANALYZE place;
