-- df place_enum: word=./data/ddl_to_data_place_enum01.txt
CREATE TABLE place (
  place_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,  place_enum INT
  -- df: text=place_enum length=1 
  ,  address TEXT 
  ) ;

