-- df place_enum: word=./data/ddl_to_data_place_enum.txt
-- df action_enum: word=./data/ddl_to_data_action_enum.txt
CREATE TABLE enum_value (
  enum_value_id INT PRIMARY KEY
  -- df: text=place_enum length=1 
  ) ;
CREATE TABLE place ( --df: mult=2.0
  place_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,  place_enum INT REFERENCES enum_value (enum_value_id)
  -- df: text=place_enum length=1 
  ,  address TEXT 
  ,  action_enum INT REFERENCES enum_value (enum_value_id)
  -- df: text=action_enum length=1 
  ) ;


