
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table enum_value (5)
\echo # filling table enum_value (5)
COPY enum_value (enum_value_id) FROM STDIN (ENCODING 'utf-8');
1
2
3
4
5
\.

-- fill table place (5)
\echo # filling table place (5)
COPY place (place_enum,address) FROM STDIN (ENCODING 'utf-8');
2	address_4_
4	address_5_5_5_5_
1	address_5_5_5_5_
5	address_5_5_5_5_
5	address_3_3_3
\.

-- restart sequences

-- analyze modified tables
ANALYZE enum_value;
ANALYZE place;
