
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table place (5)
\echo # filling table place (5)
COPY place (place_id,place_enum,address) FROM STDIN (ENCODING 'utf-8');
1	5	address_2_2_2_2_
2	1	address_4_
3	4	address_1_
4	5	address_4_
5	3	address_4_
\.

-- restart sequences

-- analyze modified tables
ANALYZE place;
