
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table place (5)
\echo # filling table place (5)
COPY place (place_id,place_enum,address) FROM STDIN (ENCODING 'utf-8');
1	1	address_1_
2	5	address_1_
3	1	address_3_3_3
4	2	address_1_
5	1	address_5_5_5_5_
\.

-- restart sequences

-- analyze modified tables
ANALYZE place;
