CREATE TABLE Order_Line ( 
  --order_line_id SERIAL PRIMARY KEY,
  order_line_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id TEXT
  --,CONSTRAINT order_line_pk PRIMARY KEY (order_line_id)
  );
CREATE TABLE Plan (
  plan_id TEXT,
  title TEXT
  );
CREATE TABLE Pln_Orl (  --df: mult=2.0
  plan_id TEXT,
  order_line_id INT REFERENCES Order_Line (order_line_id) ON UPDATE CASCADE
  );
