-- df place_enum: word=./data/place_enum.txt
CREATE TABLE enum_value (
  enum_value_id INT PRIMARY KEY
  -- df: text=place_enum length=1 
  ) ;
CREATE TABLE place (
  place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,  place_enum INT  REFERENCES enum_value (enum_value_id)
  -- df: text=place_enum length=1 
  ,  address TEXT 
  ) ;


