
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table place (5)
\echo # filling table place (5)
COPY place (place_enum,address) FROM STDIN (ENCODING 'utf-8');
3	address_4_
1	address_5_5_5_5_
1	address_5_5_5_5_
5	address_4_
5	address_2_2_2_2_
\.

-- restart sequences

-- analyze modified tables
ANALYZE place;
