---
title: "Data Generation Methods"
author: "Mert Nuhoglu"
subtitle: Alternative Ways to Generate Full Database to Test Data Model and APIs
output:
  html_document: default
path: ~/projects/study/problem/data_generation/data_generation.Rmd
---

```{r load_packages, include=FALSE}
   library(dplyr)
```

## Problem

- My ultimate goal is to make a backend API for some data model.
- I want to test and find:
  - Is data model correct?
  - What are the correct SQL/data queries?
- As input, I have yuml/uml data model
- I want to build DDL and test data for this yuml data model automatically.
- Then I will be able to write and test SQL/data queries to see if the model is correct?

## Tools

    jupyter
      %%sql postgresql://superuser:superuserpass@localhost/app
        select * from api.todos;
    anosql
      queries = anosql.load_queries('postgres', 'sql/study01.sql')
      queries.select1(conn)
    Sample Data Generator: datafiller
      !datafiller --size=100 sql/library.sql > sql/library_test_data.sql
    DDL Generator from Data: ddlgenerator
      !ddlgenerator postgresql sql/sample_data01.csv > sql/sample_data01.ddl

## Development Process

1. build data model. ex `[Company] - [Depot]`
2. write ddl. ex `CREATE TABLE company (..)`
3. write views. ex `CREATE VIEW company as SELECT company_id, ...`
4. generate sample data. ex `datafiller model.sql > sample_data.sql`
5. write rest calls. ex `/rpc/report_route_seq` `/rest/route_seq?plan_id=eq.1&select(route_seq_id,route())`
6. test sql queries

Process is documented here:

{{yuml_to_data_process.Rmd}}

