
-- data generated by /usr/local/bin/datafiller version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table product (3)
\echo # filling table product (3)
COPY product (product_id,title) FROM STDIN (ENCODING 'utf-8');
1	kia jant fk 4
2	dacia kaporta 392
3	kia balans 1.3 j
\.

-- fill table purchase_order (3)
\echo # filling table purchase_order (3)
COPY purchase_order (purchase_order_id) FROM STDIN (ENCODING 'utf-8');
1
2
3
\.

-- fill table order_line (9)
\echo # filling table order_line (9)
COPY order_line (product_id,purchase_order_id,amount) FROM STDIN (ENCODING 'utf-8');
3	1	5
2	2	2
2	1	4
3	2	1
2	3	5
3	3	1
1	1	1
1	2	2
1	3	2
\.

-- restart sequences
ALTER SEQUENCE product_product_id_seq RESTART WITH 4;
ALTER SEQUENCE purchase_order_purchase_order_id_seq RESTART WITH 4;

-- analyze modified tables
ANALYZE product;
ANALYZE purchase_order;
ANALYZE order_line;
