---
title: "Database Implementation in VRP"
date: 2018-07-31T11:26:31+03:00 
draft: true
description: ""
tags:
categories: database, vrp, postgresql
type: post
url:
author: "Mert Nuhoglu"
output:
  html_document:
    css: styles.css
blog: mertnuhoglu.com
resource_files:
- 
path: ~/projects/study/db/db_vrp.Rmd
state: wip
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

``` {r set-options}
options(width = 150)
options(max.print = 30)
``` 

## references

		test05 psk <url:file:///~/Dropbox/mynotes/content/code/cdb.md#r=g_10522>

## Before Starting

Start database server and postgrest:

``` bash
dmd=~/projects/itr/itr_documentation/data_model
psk=~/codes/pg/khumbuicefall
cd $psk
docker-compose up -d
``` 

## Connect to VRP Database

### Vim DB Plugin

``` vimscript
DB g:prod = postgresql://superuser:superuserpass@localhost/app
DB g:prod SELECT  "api"."todos"."id", "api"."todos"."todo" FROM  "api"."todos"
DB g:prod select * from data.client
``` 

``` 
 id |   name    |  address   | user_id |       created_on       | updated_on 
----+-----------+------------+---------+------------------------+------------
  1 | Apple     | address_1_ |       1 | 2017-07-18 11:31:12+00 | 
  2 | Microsoft | address_1_ |       1 | 2017-07-18 11:31:12+00 | 
  3 | Amazon    | address_1_ |       2 | 2017-07-18 11:31:12+00 | 
(3 rows)
``` 

### psql

``` bash
psql -c 'select * from data.client'
``` 

``` 
 id |   name    |  address   | user_id |       created_on       | updated_on 
----+-----------+------------+---------+------------------------+------------
  1 | Apple     | address_1_ |       1 | 2017-07-18 11:31:12+00 | 
  2 | Microsoft | address_1_ |       1 | 2017-07-18 11:31:12+00 | 
  3 | Amazon    | address_1_ |       2 | 2017-07-18 11:31:12+00 | 
(3 rows)
``` 

Define custom bash function to shorten `psql -c`

``` bash
function q () {
	psql -c $1 | tee >(pbcopy)
}
``` 

Usage of `q`

``` bash
q 'select * from data.client'
``` 

How to set `search_path` before making a query?

``` bash
psql -c 'set search_path=data' -c 'select * from client'
psql -c 'set search_path=data' -c '\dt'
PGOPTIONS='-c search_path=data' psql -c 'select * from client' 
PGOPTIONS='-c search_path=data' q 'select * from client' 
``` 

Multiple schemas for `search_path`

``` bash
PGOPTIONS='-c search_path=data,api' q 'select * from client' 
PGOPTIONS='-c search_path=data,api' q '\dt' 
PGOPTIONS='-c search_path=data,api' q '\dv' 
``` 

Using environment variables:

``` bash
export PGOPTIONS='-c search_path=data,api' 
q 'select * from client' 
PGOPTIONS='-c search_path=temp' 
q 'select * from client' 
``` 

### Show Table List and Meta Data

``` sql
show search_path
--    search_path   
-- -----------------
--  "$user", public
(1 row)
``` 

``` sql
\dn
--    List of schemas
--    Name   |   Owner   
-- ----------+-----------
--  api      | superuser
--  auth     | superuser
--  data     | superuser
--  pgjwt    | superuser
--  public   | postgres
--  rabbitmq | superuser
--  request  | superuser
--  settings | superuser
-- (8 rows)
``` 

``` sql
\dt
``` 

## Generating VRP Schema and Sample Data id=g_10541
	
		Generating VRP Schema and Sample Data <url:file:///~/projects/study/db/db_vrp.Rmd#r=g_10541>
		generate sample_data and ddl <url:file:///~/projects/itr/itr_documentation/doc_itr.md#r=g_10542>

### walkthrough

#### Requirements

``` bash
export DATA_MODEL_DIR=~/projects/itr/walkthrough_vrp/dm
export VRP_PSK_DIR=$HOME/codes/pg/vrp_psk
``` 

#### Overview 

``` bash
git clone git@bitbucket.org:mertnuhoglu/walkthrough_vrp.git
git checkout yuml2data01
git co yuml2data01-step00
git co yuml2data01-step01
git co yuml2data01-step02
``` 

#### step00: have data_model files ready

``` bash
$ tree
.
├── README.md
├── run_step01
├── run_step02
├── template_data_model
│   ├── rdb
│   │   └── def
│   │       ├── enum_value.xlsx
│   │       └── enum_var.xlsx
│   └── schema
│       ├── gen
│       └── yuml
│           ├── datamodel_enum.md
│           ├── datamodel_location.md
│           ├── datamodel_order.md
│           └── datamodel_shipment.md
``` 

#### step01: generate ddl.sql and sample_data/entity.sql

``` bash
cd ~/projects/itr/walkthrough_vrp
rm -rf dm
cp -R template_data_model dm
export DATA_MODEL_DIR=~/projects/itr/walkthrough_vrp/dm
./run_step01
``` 

Input:

		dm/rdb/def/enum_value.xlsx
		dm/rdb/def/enum_var.xlsx
		dm/schema/yuml/datamodel_enum.md
		dm/schema/yuml/datamodel_location.md
		dm/schema/yuml/datamodel_order.md
		dm/schema/yuml/datamodel_shipment.md

Generated:

		dm/schema/gen/ddl.sql
		dm/sample_data/reset_vrp.sql
		dm/sample_data/sql_insert/sql_insert_enum_value.sql
		dm/sample_data/sql_insert/sql_insert_enum_var.sql

``` bash
.
├── README.md
├── dm
│   ├── data
│   │   └── verify
│   │       └── assert_no_intersection_.tsv
│   ├── rdb
│   │   ├── def
│   │   │   ├── enum_value.xlsx
│   │   │   └── enum_var.xlsx
│   │   ├── img
│   │   └── view
│   │       ├── data_entity.tsv
│   │       ├── data_entity_with_ddl.tsv
│   │       ├── data_field.tsv
│   │       ├── datamodel_sdb.yuml
│   │       ├── datamodel_sdb_p01.yuml
│   │       └── yuml_data_model.csv
│   ├── sample_data
│   │   ├── sql_delete
│   │   │   ├── sql_delete_enum_value.sql
│   │   │   └── sql_delete_enum_var.sql
│   │   ├── sql_insert
│   │   │   ├── sql_insert_enum_value.sql
│   │   │   └── sql_insert_enum_var.sql
│   │   ├── sql_insert_no_fk
│   │   │   ├── sql_insert_no_fk_enum_value.sql
│   │   │   └── sql_insert_no_fk_enum_var.sql
│   │   └── sql_update
│   │       ├── sql_update_enum_value.sql
│   │       └── sql_update_enum_var.sql
│   ├── schema
│   │   ├── gen
│   │   │   └── ddl.sql
│   │   ├── img
│   │   └── yuml
│   │       ├── datamodel_enum.md
│   │       ├── datamodel_location.md
│   │       ├── datamodel_order.md
│   │       └── datamodel_shipment.md
│   └── yuml
│       └── img
│           ├── datamodel_enum_yuml.txt
│           └── simple_datamodel_enum_yuml.txt
├── run_step01
├── run_step02
├── template_data_model
│   ├── rdb
│   │   └── def
│   │       ├── enum_value.xlsx
│   │       └── enum_var.xlsx
│   └── schema
│       ├── gen
│       └── yuml
│           ├── datamodel_enum.md
│           ├── datamodel_location.md
│           ├── datamodel_order.md
│           └── datamodel_shipment.md

43 directories, 38 files
``` 

#### step02: generate `sample_data.sql`

``` bash
cp dm/schema/gen/ddl.sql dm/schema/gen/ddl_m.sql
``` 

Edit `ddl_m.sql` to add `datafiller` annotations

Edit `dm/init.sql`

``` bash
cd ~/projects/itr/walkthrough_vrp
export DATA_MODEL_DIR=~/projects/itr/walkthrough_vrp/dm
./run_step02
``` 

Input:

		dm/schema/gen/ddl_m.sql

Generated:

		dm/sample_data/sample_data.sql

``` bash
$ tree
.
├── README.md
├── dm
│   ├── data
│   │   └── verify
│   │       └── assert_no_intersection_.tsv
│   ├── init.sql
│   ├── rdb
│   │   ├── def
│   │   │   ├── enum_value.tsv
│   │   │   ├── enum_value.xlsx
│   │   │   ├── enum_var.tsv
│   │   │   └── enum_var.xlsx
│   │   ├── img
│   │   └── view
│   │       ├── action_enum.txt
│   │       ├── data_entity.tsv
│   │       ├── data_entity_with_ddl.tsv
│   │       ├── data_field.tsv
│   │       ├── datamodel_sdb.yuml
│   │       ├── datamodel_sdb_p01.yuml
│   │       ├── place_enum.txt
│   │       ├── route_stop_enum.txt
│   │       └── yuml_data_model.csv
│   ├── sample_data
│   │   ├── sample_data.sql
│   │   ├── sql_delete
│   │   │   ├── sql_delete_enum_value.sql
│   │   │   └── sql_delete_enum_var.sql
│   │   ├── sql_insert
│   │   │   ├── sql_insert_enum_value.sql
│   │   │   └── sql_insert_enum_var.sql
│   │   ├── sql_insert_no_fk
│   │   │   ├── sql_insert_no_fk_enum_value.sql
│   │   │   └── sql_insert_no_fk_enum_var.sql
│   │   └── sql_update
│   │       ├── sql_update_enum_value.sql
│   │       └── sql_update_enum_var.sql
│   ├── schema
│   │   ├── gen
│   │   │   ├── ddl.sql
│   │   │   └── ddl_m.sql
│   │   ├── img
│   │   └── yuml
│   │       ├── datamodel_enum.md
│   │       ├── datamodel_location.md
│   │       ├── datamodel_order.md
│   │       └── datamodel_shipment.md
│   └── yuml
│       └── img
│           ├── datamodel_enum_yuml.txt
│           └── simple_datamodel_enum_yuml.txt
├── run_step01
├── run_step02
├── tags
├── template_data_model
│   ├── rdb
│   │   └── def
│   │       ├── enum_value.xlsx
│   │       └── enum_var.xlsx
│   └── schema
│       ├── gen
│       └── yuml
│           ├── datamodel_enum.md
│           ├── datamodel_location.md
│           ├── datamodel_order.md
│           └── datamodel_shipment.md
└── walkthrough_vrp.Rproj

28 directories, 43 files

``` 

#### step03: copying data model files to vrp psk directory

``` bash
cd ~/projects/itr/walkthrough_vrp
export DATA_MODEL_DIR=~/projects/itr/walkthrough_vrp/dm
export VRP_PSK_DIR=$HOME/codes/pg/vrp_psk
./run_step03
``` 

Edit PSK sql files by adding `\ir` statements according to `~/projects/itr/walkthrough_vrp/template_data_model/init.sql`


