#!/bin/sh

# Title: Write grep `gtd` outputs to files #prg/bash #f/myst
# Date: 20240605
#
#
# Usage:
#

echo $(date +"%Y%m%d-%H%M%S") started: grep_2_file_4_gtd_by_all.sh

~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh ""
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/beyza"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/can-turkun"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/deniz"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/huseyin"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/merve"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/oguzhan"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/alp-tanyeri"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/bilge-atalay"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/doruk-uzunarslan"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/hakan-gul"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/nil-gurler"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/ozgur-nuhoglu"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/seyithan-engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/ekrem"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/mert"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/analysis"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/dev"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/figma-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/marketing"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/rpa"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/rpa-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#p/shiny-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/analysis"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/dev"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/management"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/hr"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/kms"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/marketing"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/opal"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/rpa"
~/prj/study/script/grep_2_file_4_gtd_by_person_cllb.sh "#org/training"

~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh ""
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/beyza"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/can-turkun"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/deniz"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/huseyin"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/merve"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/oguzhan"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/alp-tanyeri"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/bilge-atalay"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/doruk-uzunarslan"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/hakan-gul"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/nil-gurler"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/ozgur-nuhoglu"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/seyithan-engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/engin"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/ekrem"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/mert"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/analysis"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/dev"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/figma-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/marketing"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/rpa"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/rpa-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#p/shiny-intern"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/analysis"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/dev"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/management"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/hr"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/kms"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/marketing"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/opal"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/rpa"
~/prj/study/script/grep_2_file_4_gtd_by_person_myr.sh "#org/training"

echo $(date +"%Y%m%d-%H%M%S") completed: grep_2_file_4_gtd_by_all.sh

