---
title: "Study Emacs"
author: "Mert Nuhoglu"
output:
  html_document: default
    toc: true
    toc_float: true
---

# Tasks

		SPC T n			| switch to next theme listed in dotspacemacs-themes
		SPC f e d		| open ~/.spacemacs
		SPC ?				| search for key bindings
		SPC SPC			| list and search all commands
		SPC f				| file related commands
		SPC f t			| neotree file browser
		SPC q r			| restart emacs
		SPC f s			| save file
		SPC f S			| save file all
		SPC f e R		| reload .spacemacs
		RET					| jump/goto link
		SPC TAB			| switch to other buffer

Bind Command key to Meta and Alt key to itself:

		M-x customize-group ns > Ns Command Modifier = meta

		Alt -> none
		Command -> meta

## Escape to evil normal mode

`C-g C-z` quit

## Check Current Mode

### Article: Emacs: What's Major Mode

http://ergoemacs.org/emacs/emacs_whats_major_mode.html

Ex: turn on shell mode:

`M-x shell` 

Most basic mode: `fundamental-mode`

List all modes

`M-x apropos-command` -mode

## Setup Clojure For Spacemacs

opt03: bir clojure dosyası aç

https://medium.com/@jgolden/four-questions-every-marketplace-startup-should-be-able-to-answer-defb0590e049

opt01: Edit `~/.spacemacs`

Add: `clojure` to `dotspacemacs-configuration-layers`

Restart: SPC q r

## Custom keybindings for emacs

opt01: SPC h SPC > Spacemacs > Binding keys

		(global-set-key (kbd "C-]") 'forward-char)

opt02: vim editing style

		(define-key evil-insert-state-map (kbd "C-]") 'forward-char)

opt03: behind a leader key

		(spacemacs/set-leader-keys "C-]" 'forward-char)

# Tools

## Rainbow Parantheses for Vim

https://github.com/junegunn/rainbow_parentheses.vim

``` bash
Plug 'junegunn/rainbow_parentheses.vim'
``` 


# Evil Tutor

		SPC h T

		^j ^k down/up by section
		^h ^l	left/right

		:qa! quit
		:wqa save and quit
		M-x evil-tutor-start	| resume tutorial

# Spacemacs

## Install Spacemacs

https://github.com/syl20bnr/spacemacs#macos

``` bash
brew tap d12frosted/emacs-plus
brew install emacs-plus
rm /Applications/Emacs.app
ln -s /usr/local/Cellar/emacs-plus/*/Emacs.app/ /Applications/
``` 

## QuickStart Spacemacs

https://www.spacemacs.org/doc/QUICK_START

### 1 Configuration layers

`configuration layer`: self-contained unit

`~/.spacemacs` controls which layers to load

configuration layer: a directory with `packages.el` file

`packages.el` defines packages to be downloaded

### 4 Learning Spacemacs

``` bash
dotspacemacs-editing-style 'vim
``` 

Leader keys

		SPC	space key
		,

Evil tutor

		SPC h T

# Article: How to Use Emacs, an Excellent Clojure Editor | Clojure for the Brave and True

https://www.braveclojure.com/basic-emacs/

``` bash
cd ~/codes/emacs
git clone https://github.com/flyingmachine/emacs-for-clojure/
``` 

## REPL

		M-x cider-jack-in

# Article: Spacemacs (Vim mode) Cheatsheet

https://simpletutorials.com/c/3036/Spacemacs

		SPC q q					| quit
		SPC z x					| font size
		SPC f f					| open file
		SPC f f					| create file
		SPC f s					| save file
		SPC b b					| reopen file

		g c							| comment out 

# Article: Mastering Eshell - Mastering Emacs

https://www.masteringemacs.org/article/complete-guide-mastering-eshell

## Overview

It doesn't support interactive programs. You need `ansi-term` for this.

It is not bash or zsh. 

## Commands

# Article: Migrating from Vim

https://www.spacemacs.org/doc/VIMUSERS.html

## Basic

### 3.1 Terms

Modes vs States

vim: visual mode, insert mode

emacs: evil-insert-state

minor-mode

Layers:

layers similar to vim plugins

Transient-states

run similar commands without repeatedly pressing <Leader> key

pattern: `<Leader> <group> .`

`q` exit

### Keybinding conventions

`<Leader>`: `SPC`

`SPC m`: keybindings for language specific commands

### Buffer and window management

buffers: same in vim and emacs.

		SPC b					| keybindings for buffers
		SPC b	b 			| create a buffer / search open buffers
		SPC b	n 			| next buffer 
		SPC b	p 			| prev buffer 

# Article: Introduction · Clojure development with Spacemacs & Cider

https://practicalli.github.io/spacemacs/

Layers:

## Enhance Clojure experience · Clojure development with Spacemacs & Cider

https://practicalli.github.io/spacemacs/install-spacemacs/enhance-clojure-experience.html

Available layers

		SPC h SPC		| list layers
		TAB / RET		| doc of layer

Smartparens 

Evil Safe Structural Editing
 
		SPC m T s		| enable evil safe editing

Enable for all modes:

``` bash
(spacemacs/toggle-evil-safe-lisp-structural-editing-on-register-hooks)
``` 

Open Maximised / Full Screen 

``` bash
dotspacemacs-fullscreen-at-startup t

dotspacemacs-maximized-at-startup t
``` 

Line Numbers

		SPC t n
		SPC t r		| relative line numbering

		SPC j l		| jump to line

``` bash
dotspacemacs-line-numbers 'relative
``` 

## Spacemacs Basics 

Space bar - main menu: `SPC SPC`

Spacemacs Help system

		SPC h SPC		| help documents
		SPC h d f		| help on function
		SPC h d k		| help on keybinding

### Emacs Basics

		File
		Buffer
		Window
		Frame
		Status
		Minibuffer

#### Working with windows

		SPC 1			| jump to window 1
		SPC w			| open window menu
		SPC w .		| window transient menu
		SPC w 2		| 2 window layout
		SPC w m		| maximize window
		SPC w d		| delete window 

Golden ration

### Vim Basics 

## Working with Projects 

### File menu

		SPC f	  		| file menu
		SPC f	f 		| open file anywhere
			TAB				| complete filename
			^h				| parent dir
			^y				| paste kill ring
			^j ^k			| down/up
		SPC f	f 		| create file

### Buffer management

		SPC b	b 		| list open buffers
		SPC b	. 		| buffer transient state
			n					| cycle next
			N / p			| cycle prev
			k					| kill current buffer

### Projectile menu

A project can be:

- .git directory
- a clojure leiningen project
- a .projectile file

		SPC /				| search in project
		SPC p				| project menu
		SPC p	f 		| open file in project
		SPC f	f 		| open file in folder
		SPC p	b 		| open buffer in project
		SPC p	a 		| toggle between test/code files
		SPC p	% 		| search + replace text in project

### Layouts

		SPC l	  		| layout transient state


### File managers

#### Ranger

		SPC a	r 		| open ranger
			j/k
			h/l				| parent/child
			q					| quit

## Create a Clojure Project

https://practicalli.github.io/spacemacs/create-a-project/

``` bash
cd /Users/mertnuhoglu/projects/study/emacs/ex/study_emacs
lein new ex01
``` 

### Using emacs eshell

		SPC SPC eshell 		| run a terminal
		, '  							| start new repl (cider-jack-in)
		, s s							| switch repl/editor
		, s q							| quit repl
		, e e							| eval prev expression
		, e f							| show expression result
		SPC m s c					| connect to an existing repl
		, s n							| eval namespace of current file

states:

		i		vim insert state
		^z	emacs state
			,		repl commands

# Spacemacs DOCUMENTATION

https://www.spacemacs.org/doc/DOCUMENTATION#editing-styles

## 8 Concepts

### 8.1 Editing Styles

### 8.2 States

10 states

		normal	orange
		insert	green
		visual	gray
		motion	purple
		emacs	blue
		replace	chocolate
		hybrid	blue
		evilified	light brown
		lisp	pink
		iedit	red
		iedit-insert	red

## 14 Commands

### 14.1.2 Executing Vim and Emacs ex/M-x commands

		ex command	:
		Emacs M-x		SPC SPC

### 14.2 Reserved for user

		SPC o
		SPC m o

Ex:

``` bash
(spacemacs/set-leader-keys "oc" 'org-capture)
``` 

This binds `SPC o c` to run org mode capture 

### 14.3 Completion

Helm:

Return (escape) to helm minibuffer: `SPC w b`

Helm transient state: like vim unite/fzf

		s-M-SPC

### 14.4 Discovering

Which-key:

Help buffer displayed: `SPC`

Getting help (introspection)

		SPC h d
			b	bindings
			c	current character
			f	function
			k	key
			K	keymap

Other help key bindings:

		SPC h SPC			| spacemacs documentation using helm
		SPC h i  			| search in info
		SPC h m  			| search man pages

Available Layers

		SPC h SPC			| help-spacemacs-help

New packages

		package-list-packages

New packages (opt): Paradox

		SPC a k				| launch paradox
		f k						| filter keywords
		s							| star
		S *						| sort by star

Toggles

		SPC h t				| helm-spacemacs-help-toggles

# Article: Emacs: M-x customize Tutorial

http://ergoemacs.org/emacs/emacs_custom_system.html

Textual GUI system for setting user preferences.

		M-x customize

Ref: `49.1 Easy Customization Interface <url:/Users/mertnuhoglu/projects/study/emacs/study_emacs.Rmd#tn=49.1 Easy Customization Interface>`

# Article: Emacs Manual

## 49.1 Easy Customization Interface

Settings

Most `settings` are `customizable variables` also called `user options`

`M-x customize` opens `customization buffer` 

### 49.1.1 Customization Groups

Master group: `Emacs`

Hierarchical groups. 

# Spacemacs Help Documents

		SPC h SPC		| spacemacs manuals

## Migrating from Vim

### Transient States

		SPC <group> .

## Spacemacs conventions

		SPC m				| major mode keybindings
		
### Key bindings conventions

#### Markup

		SPC m h				| header bindings
		SPC m i				| insert ...

### Running commands

		:							| ex commands
		SPC SPC				| emacs commands

### Buffer and window management

		SPC b b				| buffer
		SPC b d				| buffer kill

^W komutlarının karşılıkları:

		SPC w s				| window split 
		SPC w j				| window navigate
		SPC w d				| buffer kill

---

Files

		SPC f f				| file open
		SPC f r				| file recent
		SPC f s				| file save :w

Help

		SPC h d f				| doc function 
		SPC h d k				| doc keybinding
		SPC <F1>				| search doc

Exploring

		SPC h SPC				| list layers
		SPC ?    				| list keybindings
		
## Customization

`.spacemacs` file

4 functions:

		dotspacemacs/layers
		dotspacemacs/init
		dotspacemacs/user-init
		dotspacemacs/user-config

### Emacs Lisp

Setting variable value:

		(setq variable value)

Keybindings

		(define-key map new-keybinding function)

Functions

		(defun func-name (args) body)

Layers

Installing a package

		dotspacemacs-additional-packages

Loading packages

		(use-package package-name :defer t)

# Article: Spacemacs - First Impressions From an Emacs Driven Developer | jr0cket

http://jr0cket.co.uk/2015/08/spacemacs-first-impressions-from-an-emacs-driven-developer.html

## Navigating with Helm

Emacs: `M-x command-name`

Spacemacs: `SPC ...`

Commands are grouped:

		S	spelling
		T	themes
		a	applications
		b	buffers
		f	files
		g	git

Helm: incremental completion and selection

## Other features

numbered buffers: `SPC <number>`

smartparens:

smooth scrolling

# Article: Helm Manual

https://github.com/emacs-helm/helm/wiki

minibuffer

completion window

Use RET instead of TAB for completion

# Article: A Package in a league of its own: Helm

http://tuhdo.github.io/helm-intro.html

Eğer seçilecek çok sayıda öğe varsa:

- C-SPC	mark candidates
- C-c C-i insert into current buffer

# Article: which-key

https://github.com/justbur/emacs-which-key

A minor mode

It displays available key bindings after prefix like `C-x`

# Article: Emacs Mini Manual (PART 1) - THE BASICS

http://tuhdo.github.io/emacs-tutor.html

## Appendix

### Why Emacs

A development platform. A virtual machine that interprets its own code. 

``` bash
(defun hello ()
  (interactive)
	(message "Hello"))
``` 

### Emacs history

Lisp Machine

"The Ghost in the Lisp Machine"

## Programming

Jump to any source file

Autocompletion

Showing function arguments

Comment multiple lines

Debugger GDB

Diff between current and latest revision

Magit: 

Live grep

Select any file quickly

PDF Reader

## Why this guide?

### A bit of history

### Swap Control and Capslock

## Concepts

### Command

Any key calls `self-insert-command`

2 types of functions:

- Normal functions
- Commands: interactive

`M-x` is `execute-extended-command`

### Emacs Key Notation

``` bash
C-
M-
S-
DEL
RET
SPC
ESC
TAB
``` 

Prefix key: `C-x r l`. Here `C-x r` is prefix.

List all commands with a prefix: Append `C-h` 

Ex: `C-x r C-h` list all commands after `C-x r`

`C-g` executes `keyboard-quit`. It cancels any key sequence.

### Keys are easy to remember

`C-x` for default and global bindings

`C-c` for users to customize

`C-u` for altering behaviors of commands

`C-<number>` for repeating command

### Ask for help

#### Built-in help

`C-h m` runs `describe-mode`

`C-h w` runs `where-is` to get keybindings of a command

`C-h c` runs `describe-key-briefly` opposite of `where-is`

`C-h k` runs `describe-key` opposite of `where-is` including documentation

`C-h e` runs `view-echo-area-messages`

`C-h v` runs `describe-variable` also allows customization.

`C-h C-h` runs `help-for-help`

`<Prefix> C-h` lists all commands with `<Prefix>`

#### Apropos

https://www.gnu.org/software/emacs/manual/html_node/emacs/Apropos.html

apropos pattern: a word, a list of words, or a regex

Ex: Answer to: What are the commands for working with files?

`C-h a` runs `apropos-command`: search for commands

`M-x apropos` runs : search for functions and variables

#### Info

`M-x info` `C-h i` info manual

`M-x info-emacs-manual` `C-h r` info manual

#### Man

`M-x man` man of a unix command

`M-x woman`

### Point

### Opening Files

`M-x find-` TAB

`M-x find-file` TAB

`C-x C-f` runs `find-file`

Select a path `~/.spacemacs` > `M-x find-file-at-point` or `g f`. The file is opened.

### Ido mode

Interactively Do Things

`M-x ido-mode`

## Bookmark

`C-x r m` runs `bookmark-set`

`C-x r b` runs `bookmark-jump`

`C-x r l` runs `bookmark-bmenu-list`

Mnemonics:

`r` for Return to somewhere

`b` switch Buffer

## Motion 

## Navigating pairs

`C-m-f` runs `forward-sexp`

# Article: Smartparens Emacs and Pairs

https://ebzzry.io/en/emacs-pairs/

# Article: Spacemacs + Clojure

https://joyheron.com/post/sketchnote/clojure-meetup/2017/08/17/spacemacs.html

		M-m p t				| project tree file manager
		,							| clojure specific menu
		M-m b n				| switch between buffers
		M-x SPC				| list of all commands
		SPC SPC				| list of all commands (spacemacs)

`SPC` replaces `M-x` prefix in Spacemacs.

Start repl:

		M-x cider-jack-in		| opt01
		
opt02:

``` bash
lein repl
M-x cider-connect
``` 

Install in `~/.lein/profiles.clj`

https://github.com/clojure-emacs/cider-nrepl

``` bash
:plugins [[cider/cider-nrepl "0.15.0"]]
``` 

Evaluating

`C-c C-k` evaluates the whole namespace

`C-c C-e` evaluates inline

`C-c C-p` evaluates and prints 



