---
title: "Youtrack İçindeki Custom Fieldlara Erişmek"
output: html_document
---

# Class (Object Type) Hiyerarşisi

Üç tane obje tipi var bununla ilgili:

1. `CustomField`
2. `ProjectCustomField`
3. `IssueCustomField`

Şimdi biz Youtrack'te yeni bir custom field oluşturuyoruz diyelim admin panelini kullanarak.

Bu durumda yeni bir `CustomField` kaydı oluşturuluyor.

Daha sonra bu custom field'ı belli bir projede kullan diyoruz. Bu durumda, o `CustomField` altında bir `ProjectCustomField` kaydı oluşturuluyor.

Daha sonra, o projedeki bir issue içine giriyoruz ve o custom fieldın içine bir değer koyuyoruz. Bu da bir `IssueCustomField` kaydı oluşturuyor.

## Youtrack içinde `Requirement ID` custom fieldına erişmek:

`requirement_id` alanını biz YT'de custom olarak oluşturmuştuk. Ona nasıl erişeceğiz?

Bunun için önce e07c.sh scriptinde REST çağrısıyla tüm Custom Fieldların listesini çektik ve aradığımız field'ın id'sini bulduk:

REST: `https://youtrack.layermark.com/api/admin/customFieldSettings/customFields?fields=id,name,aliases,instances(id,project(id,name))`

```json
{
	"project": {
		"name": "test",
		"id": "0-7",
		"$type": "Project"
	},
	"id": "111-42",
	"$type": "SimpleProjectCustomField"
},
"name": "Requirement ID",
"id": "89-39",
"$type": "CustomField"
```

Daha sonra e08.sh scriptiyle bir deneme yaptık. `Requirement ID` isimli custom fieldımız var `test` projesinde. Bunun `TEST-91` issue'suna ait değerlerini almayı test ettik:

REST: `https://youtrack.layermark.com/api/issues/TEST-91/customFields/111-42?fields=id,projectCustomField%28id,field%28id,name%29%29,value%28id,isResolved,localizedName,name%29`

Response:

```json
{
	"projectCustomField": {
		"field": {
			"name": "Requirement ID",
			"id": "89-39",
			"$type": "CustomField"
		},
		"id": "111-42",
		"$type": "SimpleProjectCustomField"
	},
	"value": 15,
	"id": "111-42",
	"$type": "SimpleIssueCustomField"
}
```

Burada öncekinden fazla olarak `value` bulunuyor: `"value": 15,`

## CustomField

Youtrack type hiyerarşisinde, CustomField diye bir type var. Bu typeın alt tipleri olarak ProjectCustomField var. Bir CustomField genel tanım. ProjectCustomField ise bu CustomField'ın belli bir projedeki örneği (instance).

Belli bir projedeki o projenin tüm alanlarını çekmek için, projenin id'sini kullanarak REST sorgusu yapmalıyız:

REST: `https://example.youtrack.cloud/api/admin/projects/0-0/customFields?fields=id,canBeEmpty,emptyFieldText,project(id,name),field(id,name)`

Burada `0-0` ilgili projenin idsi oluyor.

Bir de bu IssueCustomField var. Bu ise ProjectCustomField alanının bir issue'daki örneğini veya kaydını tutar.

REST: `https://example.youtrack.cloud/api/issues/2-7/customFields?fields=id,value(id,name,login,fullName),projectCustomField(id,field(id,name))`

Response:

```json
{
	"id":"92-1",
	"$type":"SingleEnumIssueCustomField",
	"projectCustomField":{
			"id":"92-1",
			"$type":"EnumProjectCustomField",
			"field":{
					"id":"58-1",
					"name":"Priority",
					"$type":"CustomField"
			}
	},
	"value":{
			"id":"67-2",
			"name":"Major",
			"$type":"EnumBundleElement"
	}
},
```
