---
title: "Reproducing: Introduction to Association Rules in R by Yosuke Yasuda"
date: '`r strftime(Sys.time(), "%Y-%m-%dT%H:%M:%S+03:00")`'
draft: false
description: ""
tags:
categories: r, rdb
type: post
url:
author: "Mert Nuhoglu"
output: html_document
blog: mertnuhoglu.com
resource_files:
-
path: ~/projects/study/r/convert_yuml_to_rdb_style_data.Rmd
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

``` {r set-options}
options(width = 150)
options(max.print = 30)
``` 

```{r}
library(dplyr, warn.conflicts = F)
data_model_dir = "/Users/mertnuhoglu/projects/itr/itr_documentation/data_model/"
```

This document reproduces the code explained in [Introduction to Association Rules in R by Yosuke Yasuda](https://blog.exploratory.io/introduction-to-association-rules-market-basket-analysis-in-r-7a0dd900a3e0)

```{r}
library(lubridate)
library(hms)
library(tidyr)
library(urltools)
library(stringr)
library(readr)
library(broom)
library(RcppRoll)
library(tibble)
library(dplyr)
library(exploratory)

# Data Analysis Steps
read_delim("/Users/yasudayousuke/Downloads/groceries (1).csv" , ",", quote = "\"", skip = 0 , col_names = FALSE , na = c("","NA") , locale=locale(encoding = "ASCII", decimal_mark = "."), trim_ws = FALSE , progress = FALSE) %>%
  exploratory::clean_data_frame() %>%
  mutate(transaction_id = row_number()) %>%
  gather(key, product, -transaction_id, na.rm = TRUE) %>%
  arrange(transaction_id) %>%
  do_apriori(product, transaction_id, min_support = 0.0001) %>%
  filter(support > 0.0004) %>%
  group_by(rhs) %>%
  top_n(3, lift)
```
